### ISSUE TITLE
echo and auction tests must be cleaned up and their return values checked

### ISSUE THREAD

**Issue by bvavala** [hyperledger-labs/fabric-private-chaincode#104]

**Comment by KimRasz** [comment]
Best Practice Clean Up

**Comment by annumberhocker** [comment]
@bvavala 

Adding additional calls to test each of these conditions: 
#define OK "OK"
#define AUCTION_DRAW "DRAW"
#define AUCTION_NO_BIDS "NO_BIDS"
#define AUCTION_ALREADY_EXISTING "AUCTION_ALREADY_EXISTING"
#define AUCTION_NOT_EXISTING "AUCTION_NOT_EXISTING"
#define AUCTION_ALREADY_CLOSED "AUCTION_ALREADY_CLOSED"
#define AUCTION_STILL_OPEN "AUCTION_STILL_OPEN"

I will parse the stderr message returned from the `peer chaincode` calls to get the response code. If conditions fail, I will throw an error.

Are there any other requirements for this issue?

**Comment by annumberhocker** [comment]
Issue fixed and merged with PR #146.
