### ISSUE TITLE
Upgrade to SGX SDK 2.6

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-private-chaincode#112]
We should upgrade to the new SGX SDK. This is related to #99 as version 2.6 comes with reproducible enclave builds.

**Comment by mbrandenburger** [comment]
PR #168 upgrades to SGX SDK 2.6

**Comment by g2flyer** [comment]
(Note, though, PR #168 only updates the docker FPC CC _runtime_ image to SDK 2.6, i.e., we also have to update the docu correspondingly to capture the build time.  (although docu update we might probably best combine with dcap update as it simplifies the install procedure, see the [corresponding change in PDO](corresponding https://github.com/hyperledger-labs/private-data-objects/pull/229/files)

**Comment by mbrandenburger** [comment]
> (Note, though, PR #168 only updates the docker FPC CC _runtime_ image to SDK 2.6, i.e., we also have to update the docu correspondingly to capture the build time.

SGX SDK 2.6 is listed under Requirements in the main README.md. Is something else missing?

> (although docu update we might probably best combine with dcap update as it simplifies the install procedure, see the [corresponding change in PDO](https://github.com/hyperledger-labs/private-data-objects/pull/229/files)

Regarding DCAP, I would like to move your comment to Issue #15 and close this here. WDYT?

**Comment by g2flyer** [comment]
> > (Note, though, PR #168 only updates the docker FPC CC _runtime_ image to SDK 2.6, i.e., we also have to update the docu correspondingly to capture the build time.
> 
> SGX SDK 2.6 is listed under Requirements in the main README.md. Is something else missing?

I thought we included installation info. Realize now that we  just link to the sgx sdk docu and the install-from-source variant.  In particular with dcap there is now a debian install for the base packages and dkms for auto-kernel-rebuild on upgrades.  But best to update docu correspondingly when addressing #175 

> > (although docu update we might probably best combine with dcap update as it simplifies the install procedure, see the [corresponding change in PDO](https://github.com/hyperledger-labs/private-data-objects/pull/229/files)
> 
> Regarding DCAP, I would like to move your comment to Issue #15 and close this here. WDYT?

Moved DCAP enablement to issue (#175 ) separate from #15 but otherwise agree and hence close this
