### ISSUE TITLE
Define & implement endorsement policy support

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-private-chaincode#12]
In MVP, we support only designated endorser (#273) which requires exactly a single, fixed endorser.   So not endorsement policies, in particular not the default `MAJORITY` policy will work in that case.  Following are the necessary steps:
- [x] define the sub-set of valid fabric endorsement policy expression which we support and what the semantics is
- [x] document above in `docs/design/fabric-v2+/fpc-management.md`.
- [ ] (ideally) check in `fabric/bin/peer.sh`
  - [ ] in `approveformyorg` that policy is provided explicitly and specified policy as satisfiable (note realistically with designated peer, we can never realistically rely on a default policy as single peer policy would be insecure in the general fabric case)
     - actually, one "cheapo" way to check is to call the createenclave with "invoke .... --waitForEvent".  This will actually run the specified endorsement policy and would bail iff that enclave is not from the correct org :-)
  - [ ] in `createenclave` that the peer is consistent with the specified policy.
- [x] update FPC examples (& docu) to use the endorsement policy as specified in this work item.

**Comment by mbrandenburger** [comment]
Looking at Fabric v2 documentation, I don't see how the designated peer can be implemented using the provided primitives. 

https://hyperledger-fabric.readthedocs.io/en/release-2.0/endorsement-policies.html?highlight=default%20endorsement%20policie#endorsement-policy-syntax

**Comment by mbrandenburger** [comment]
I guess a `OR('Org1.peer')` is the closest what we can get, however, this policy does not express that we only want a single specific peer.

**Comment by mbrandenburger** [comment]
I guess we have two options here.

1. Just say endorsement policy is ignored for MVP and in Peer_CLI we set it to `any org` and enforce the designated peer/enclave through fpc-vscc and ERCC. We could restrict ERCC to register only a single enclave per chaincode. In fpc-vscc we invalidate every transaction from an enclave that is not registered. The documentation should mention that any endorsement policy is ignored for FPC_Chaincodes.

1. Implement CCKeyImport/Export and support any form of `OR(...) endorsement policy.

**Comment by g2flyer** [comment]
> I guess a `OR('Org1.peer')` is the closest what we can get, 

That would have been my take. 

> however, this policy does not express that we only want a single specific peer and therefore any peer or Org1 can endorse.

I don't think we have to implement it to the letter, we can further restrict it by saying only a single peer for that org will have `createenclave` called for it and the clients have to make sure that they call the correct peer ...
