### ISSUE TITLE
Remove obsolete fabric/sgxconfig ..

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#124]
As part of documentation clean-up (#96 ) we probably also should simply get rid of fabric/sgxconfig as i think the scripts are obsolete and might not work anymore and the examples from integration are better starting points for users to look at on how to run it?

**Comment by KimRasz** [comment]
Addressed in PR #128

**Comment by mbrandenburger** [comment]
Closed with #128
