### ISSUE TITLE
Hello World tutuorial

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-private-chaincode#129]
We should add a hello world tutorial style section to the getting started section.

Briefly go through the steps a developer has to perform to write a simple private chaincode and how to deploy and test it using the integration test framework.

**Comment by g2flyer** [comment]
it should also reference `shim.h` as the programming model (but see issues #88 and #83 for what might change there)

**Comment by g2flyer** [comment]
See also issue #136

**Comment by sjanakir2015** [comment]
Here is the proposed change: 

1. Add a link to the tutorial in https://github.com/hyperledger-labs/fabric-private-chaincode/blob/master/README.md.

- Add the tutorial in a (new) README.md under examples folder.

2.  Provide complete code for 3 files, namely helloworld_cc.h, helloworld_cc.cpp and helloworld_test.sh with directions / explanations added.

**Comment by g2flyer** [comment]
> Here is the proposed change:
> 1. Provide complete code for 3 files, namely helloworld_cc.h, helloworld_cc.cpp and helloworld_test.sh with directions / explanations added.

Sounds like a good overall plan. I wonder whether we really need a new example rather than use an existing one.  I also think it would be useful to have an example which makes use of most features of the shim, e.g., use state and, as soon as added (see PR #137) also get_creator, making the auction one a better target than a minimalistic one like hello world?

**Comment by sjanakir2015** [comment]
auction example is a good example.  However, there are additional steps needed to marshall and unmarshall an auction (structure) - which takes the focus away from the shim interface.  I plan to use a simple asset and its value stored in the ledger.  (Subsequent) Calls to putData (asset1, value) modifies the value of the same asset (asset1).  getData(asset1) returns the current value of assetName1.  
It is a good idea to use all of the methods in shim.  As we add additional methods in shim, we could update the tutorial to illustrate use of the new methods.  
Also, we should identify which methods are NOT going to be exposed to developers.

**Comment by sjanakir2015** [comment]
> > Here is the proposed change:
> > 
> > 1. Provide complete code for 3 files, namely helloworld_cc.h, helloworld_cc.cpp and helloworld_test.sh with directions / explanations added.
> 
> Sounds like a good overall plan. I wonder whether we really need a new example rather than use an existing one. I also think it would be useful to have an example which makes use of most features of the shim, e.g., use state and, as soon as added (see PR #137) also get_creator, making the auction one a better target than a minimalistic one like hello world?


auction example is a good example.  However, there are additional steps needed to marshall and unmarshall an auction (structure) - which takes the focus away from the shim interface.  I plan to use a simple asset and its value stored in the ledger.  (Subsequent) Calls to putData (asset1, value) modifies the value of the same asset (asset1).  getData(asset1) returns the current value of assetName1.  
It is a good idea to use all of the methods in shim.  As we add additional methods in shim, we could update the tutorial to illustrate use of the new methods.  
Also, we should identify which methods are NOT going to be exposed to developers.

**Comment by g2flyer** [comment]
> Also, we should identify which methods are NOT going to be exposed to developers.

definitely agree on that. To separate that out is actually also part of the effort of PR #137 (see split of shim.h into shim.h and shim_internals.h).

**Comment by g2flyer** [comment]
Addressed in #142
