### ISSUE TITLE
Identify common functionality implemented now twice in C and Go (mostly crypto-related)

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-private-chaincode#130]
In many places of the current code base we have a c and go implementation of the same logic. In particular, tlcc shares a lot of logic with our custom validation plugins. The idea of this task is to identify the common code paths that we can later refactor and reuse common code as much as possible.

**Comment by g2flyer** [comment]
One example of this is enclave proposal signature generation and verification:
- ecc/crypto/ecdsa.go::Verify (for VSCC)
- tlcc_enclave/enclave/ledger.cpp::int parse_endorser_transaction (for TLCC)
- ecc_enclave/enclave/enclave.cpp

**Comment by mbrandenburger** [comment]
@bvavala can you please give a short update on the pdo crypto work here.

**Comment by mbrandenburger** [comment]
Common crypto module based on PDO crypto was added with #337.
