### ISSUE TITLE
Add custom data (e.g. TLCC MRENCLAVE) to genesis block

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-private-chaincode#131]
The genesis block defines the root of trust of a blockchain. Therefore, it seems to be the ideal place to put security sensitive information such as the MRENCLAVE of TLCC. This information should then be accessible during transaction validation phase when enclave-created transactions are processed.

The purpose of this task is to identify ways how to extend or add custom data to a channel genesis block and consume them.

For instance, one possible solution is to create FPC specific configuration transactions. But what does it need to create those config transactions?

Also could MRENCLAVE be added by using the configtxgen tool? 

There may exist multiple ways how to implement this. Is there a short term quick and dirty solution and a long-term elegant and clean solution?

Last, implement this.

**Comment by g2flyer** [comment]
obsolete now. new design handles that via encoding in version number or baked into ercc
