### ISSUE TITLE
Evaluating new deployment model vs old chaincode-type

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-private-chaincode#132]
Currently, we integrate FPC using our go-wrapper chaincode and the docker image override hack. A proper integration, however, requires a more elegant way. There are apparently two possible ways to do the integration better. First, the new deployment model (Fabric 2.0 feature) using the external Launcher vs the old chaincode-language model.

The task is to evaluate the two models and then implementing the best choice.

**Comment by g2flyer** [comment]
Some discussion in https://drive.google.com/open?id=1fJZCu5ehQSgN4jlCdJ1BYjWY3CXWu7krgEa_Av2hLF8 and https://drive.google.com/open?id=1ewl7PcY9t27lScv2O2VaeHMsk13oe5B2MqU-qzDiR80

Also have to consider Murali proposal ....

**Comment by g2flyer** [comment]
Core issues addressed by #320
