### ISSUE TITLE
Add custom data (e.g. ECC_MRENCLAVE) to chaincode definition

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-private-chaincode#133]
With new lifecycle v2 each organization must approve a so-called chaincode definition before a chaincode is "instantiated".

As this approval mechanism is great to also agree on the enclave code, in particular ECC_MRENCLAVE, we should leverage this here. Currently, we use a hard-coded ECC_MRENCLAVE and write it to the ledger using during chaincode instantiate (just for simplicity).

This task builds the foundation for the new ERCC model.

The purpose of this task is to identify ways how to extend or add custom data to a chaincode definition. Maybe existing fields can be used ("hijacked").

Last, implement this.

**Comment by mbrandenburger** [comment]
The latest design of FPC uses the concept of the chaincode definition to let the parties to agree on the MRENCLAVE of a FPC chaincode. See https://github.com/hyperledger-labs/fabric-private-chaincode/blob/cr2.0.0/docs/design/fabric-v2%2B/fpc-lifecycle-v2.puml

**Comment by mbrandenburger** [comment]
The chaincode definition can be accessed through lifecycle. See https://github.com/hyperledger-labs/fabric-private-chaincode/issues/361#issuecomment-646610010

**Comment by g2flyer** [comment]
resolved in new design as encoding in version field (MRENCLAVE) and baking in into ERCC (e.g., IAS keys, TLCC MRENCLAVE ..)
