### ISSUE TITLE
New ERCC model

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-private-chaincode#134]
The current ERCC model comes with some drawbacks:
  - Single-endorser policy only + Custom validation at __every__ peer
  - ERCC must contact IAS (Internet connection and IAS credentials needed)
  - Current impl: No way to securely pass credentials to ERCC only
  - for EPID attestation SPID is needed when quote is created (ECC must provide this)

The purpose if this task is to design a new ERCC model that overcomes these limitations.

Last, implement this.

**Comment by mbrandenburger** [comment]
#116 proposes a new design.

**Comment by mbrandenburger** [comment]
#116 merges an intermediated version into _new_design_ branch.

**Comment by mbrandenburger** [comment]
@bvavala Do you want to take over this issue?

**Comment by mbrandenburger** [comment]
PR #371 had a good discussion regarding ERCC validation. This may help when implementing new ERCC scheme and moving away from ERCC custom validation.

> Why is this actually not the only/main case?  Do we currently allow updates? Otherwise, there shouldn't be anything in the state anyway? If so, how are we doing updates securely?  I realize this plugin will go away but the validation logic should transfered to some extent to ercc itself, so this code fragment is still somewhat relevant? maybe some comments could be helpful for the future?

_Originally posted by @g2flyer in https://github.com/hyperledger-labs/fabric-private-chaincode/pull/371_

**Comment by mbrandenburger** [comment]
> I guess the current code would allow wrap an ecc _setup-tx by (via cc2cc) by another tx and "hijack" the attestation and register it with a different ecc_namespace?  Per-se i don't see immediately how this leads to bad stuff but it's a bit ugly.  Ideally, i think the attestation should explicitly bind the the ecc namespace?  (Not necessarily here, but might be good to do so in the revised version? Actually, iff we implement the new registration protocol, we should do so ... :-)

_Originally posted by @g2flyer in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0NDMyNDQ1MjA1/pull_requests/unread_timeline_

**Comment by mbrandenburger** [comment]
The new ERCC model is defined in https://github.com/hyperledger-labs/fabric-private-chaincode/blob/cr2.0.0/docs/design/fabric-v2%2B/fpc-registration.puml

**Comment by mbrandenburger** [comment]
@bvavala Can we close this one as #404 already focuses on the implementation of this new design?

**Comment by bvavala** [comment]
> @bvavala Can we close this one as #404 already focuses on the implementation of this new design?

Yes, it seems appropriate.
