### ISSUE TITLE
More complex example

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#150]
While we don't know yet what the demo use-case will be, it's very likely that it will be more complex than our current one and probably involve multiple interacting change-codes, fair-exchanges/escrowed items and alik.   So it would be good to already proactively consider whether our current functional model is sufficient to implement it or whether we might need some of the additional fabric functions mentioned as comments in `shim.h` (as added by PR #137).

Probably best to study one of the more complex Fabric examples, e.g., commercial papers, and see whether FPC would allow re-implementing it.  Otherwise, we could consider extending the auction example with a separate asset chaincode where to bid you would have to escrow an asset.

This investigation should also answer whether the potential additional shim functions identified in issue #83 (and added as comments to shim.h) might be needed

**Comment by g2flyer** [comment]
Commercial Paper App:
- docu: https://hyperledger-fabric.readthedocs.io/en/master/tutorial/commercial_paper.html?highlight=commercial%20paper
- code: https://github.com/hyperledger/fabric-samples/tree/release-1.4/commercial-paper

**Comment by mbrandenburger** [comment]
Marbles Example:

https://github.com/hyperledger/fabric-samples/tree/release-1.4/chaincode/marbles02

**Comment by g2flyer** [comment]
Only other somewhat interesting (in this context) sample in fabric-sample: is [Interest_Rate_swaps](https://github.com/hyperledger/fabric-samples/tree/master/interest_rate_swaps). It illustrates use of [state-based endorsement policies](https://hyperledger-fabric.readthedocs.io/en/release-1.3/endorsement-policies.html#key-level-endorsement) where for swaps exceeding a threshold, additionally an auditor endorsement is necessary. As implemented, it doesn't really make sense  security-wise as an auditor peer whould just blindly execute the normal swap and so wouldn't add any additional audit.  That said, with new fabric lifecycle where peer could have different chaincode, auditor, though, _could_ run an augmented version of the contract which does normal transaction as well as additional audit check!! Not that sample description would discuss this (let alone code implement it).  Which in turn is kind-of good as we couldn't replicate this pattern with FPC where we need identical code!

**Comment by bvavala** [comment]
we have identified the spectrum auction as a compelling use case, we have implemented that and pushed it in the repo

**Comment by g2flyer** [comment]
> we have identified the spectrum auction as a compelling use case, we have implemented that and pushed it in the repo

Hmm, identifying a demo was not necessarily the goal of this issue, more identifying enough existing fabric use-cases to validate that our current shim.h is representative enough and we do not need any of the additional fabric functions mentioned as comments in shim.h (as added by PR #137).   But i guess we can re-visit this if we get push back on the current set of offered function in shim.h ...
