### ISSUE TITLE
TLCC signature validation fails in some cases

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#152]
.There seem to be a strange "ERROR [Enclave] Ledger: ecc signature validaion failed" in tlcc (with text in newer version having typo fixed as "ecc signature validation failed"". )

It happens only for auction test and not echo, only for create but also not for all of them (but always for the same one!). As we ignore signature validation errors in tlcc, you’ll see it only in the log-file, no program/script will fail due to it.

Existed in master as of 17f8a18e4b8289f20296bd1bafec76e2c068f2be but probably already earlier ..

**Comment by g2flyer** [comment]
Note: these failures show up also in tlcc_enclave test (as it's based now on deployment_test.sh which also cause one of these) but as tlcc only reports problem but does not fail, tests still pass.  A change in PR #137 makes now, though, at least the test verbose so the error is visible in the make output ...

**Comment by g2flyer** [comment]
Might related to issue #42 ?

**Comment by mbrandenburger** [comment]
Closed with #160
