### ISSUE TITLE
Change our examples and demo to fabric 2.0 lifecycle commands

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#165]
move from old lifecycle commands (peer chaincode install/instantiate) to new lifecycle (peer lifecycle chaincode package/approvefororg/commit).

Probably best doing in conjunction with #98 as motivation of this issue is to enable _lifecycle_ endorsement policies which can require multiple organizations (technically, we are currently limited to have (transaction) endorsements only by a single peer (TEE/SGX enclave attestation) endorsement.

Sub-work-items:
- [x] example conversion
- [X] demo (via mockserver)
- [ ] demo (via fabric network)
- [ ] demo (via fabric network and migrated from fabric-client to fabric-network)

**Comment by g2flyer** [comment]
Precondition: resolution of issue #254 and #247

**Comment by g2flyer** [comment]
Note: the demo with docker-compose is postponed to concept-release 2.1

**Comment by g2flyer** [comment]
Note: According to [fabric node-sdk migration guide](https://hyperledger.github.io/fabric-sdk-node/master/tutorial-migration.html):
- the fabric-client apis we use in `demo` (and also in `utils/docker-compose/node-sdk`) are now depricated and one should use fabric-network in turns, and
- "SDK no longer aims to provide administrative and management capability. The command-line interface should be used for these operations."
This means that we should eventually migrate the demo client side code to the new APIs.  Right now i've just added a separate checkbox above but we probably will eventually have to "outsource" checkboxes  into separate smaller work-item(s) ...

PS: Also note that demo with fabric networks depend on resolution of #256

**Comment by g2flyer** [comment]
Note: the example02 used in deployment test doesn't exist anymore, probably easiest to just replace with an example from fabric samples, e.g., marbles02 ...

**Comment by mbrandenburger** [comment]
#330 converts examples
