### ISSUE TITLE
Make contributor's guide more prominent in readme

### ISSUE THREAD

**Issue by peterschwarz** [hyperledger-labs/fabric-private-chaincode#178]
Currently the contributor's guide is hard to find in the readme (i.e. it is buried down in the Help section).  This should be highlighted in its own section.

**Comment by mbrandenburger** [comment]
What about adding a "Contributions Welcome" section to the main README.md, WDYT?

**Comment by peterschwarz** [comment]
That's sound good.  Will do.

**Comment by mbrandenburger** [comment]
fixed with #179

**Comment by mbrandenburger** [comment]
@peterschwarz Can you please post here the link to the gitflow description you mentioned in our offline discussion. Thanks
