### ISSUE TITLE
LF sunset nexus.hyperledger.org - links not working

### ISSUE THREAD

**Issue by bvavala** [hyperledger-labs/fabric-private-chaincode#212]
The links to grab the Fabric binaries hang.
This seems to be due to a [change of repos](https://lists.hyperledger.org/g/fabric/topic/hyperledger_nexus_repository/70049382?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,70049382). However, the new one does not contain the needed binaries. Also, the `boostrap` script in Fabric 1.4.4 does not seem to be updated.

The script in Fabric master should contain the right link:
https://github.com/hyperledger/fabric/blob/cb721dde8f34e329d83878babba29f0f0767386c/scripts/bootstrap.sh#L87

**Comment by g2flyer** [comment]
Closing as PR #211 does fix the issue for FPC (though not for fabric 1.4.4 ..)
