### ISSUE TITLE
Editing of bids by the bidder not working as expected in UI

### ISSUE THREAD

**Issue by Jordy24** [hyperledger-labs/fabric-private-chaincode#225]
During the rounds, the bidder does not seem to be able to change their bidding prices and quantity.
This occurs in between the rounds, so for example if the round is 3 and now as a  bidder you want to change your bidding price and quantity to meet requirements such as lowering the quantity of your bid. In the UI you are not able to do that.

**Comment by bvavala** [comment]
Can you be more specific?

Let's assume you bid for 5 channels on a territory with 10 channels, your bid is accepted, and it is the only bid. As demand does not meet supply, you are not allowed to lower your bid.

**Comment by mbrandenburger** [comment]
Can this be closed now? @Jordy24 please reference your PR here.

**Comment by Jordy24** [comment]
This bug is fixed in PR #226

**Comment by mbrandenburger** [comment]
Awesome! Thanks!
