### ISSUE TITLE
chaincode-container helper does not work with Fabric 2.0 anymore

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-private-chaincode#244]
With Fabric 1.4 `utils/fabric/get-fabric-container-name.go` uses `ccintf.CCID` to build the chaincode container name. However, this got removed with Fabric 2.0. See [here](https://github.com/hyperledger/fabric/commit/c1cd9b1a90dbd30b8233662283cb602ae463d949#diff-2689a7c963073b3c5268ae01660e6e21)

A quick patch could be:
```
	ccid := *ccName + ":" + *ccVersion
	name, _ := vm.GetVMNameForDocker(ccid)
```

Maybe this helper will eventually go away as we move towards external builders.

**Comment by g2flyer** [comment]
this helper should go away with the external builder and the removal of the switcheroo.  So quick patch seems fine although we should add a comment on from where we got that code fragment (presumably  `<fabric-core.git>/core/chaincode/chaincode_support.go:LaunchInProc()`  ?) ..
