### ISSUE TITLE
Update go chaincode imports

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-private-chaincode#247]
With Fabric 2.0 the go chaincode shim moved to a separate repo in `github.com/hyperledger/fabric-chaincode-go/shim`. Also protos have been moved to `github.com/hyperledger/fabric-protos-go/peer`. 

Must be also added to godeps and probably also move to use of go modules as done in https://github.com/hyperledger/fabric-samples/tree/master/chaincode/marbles02/go ?

Needs to be updated in the following components:
- [ ] ERCC 
- [ ] ERCC-VSCC
- [ ] TLCC
- [ ] ECC
- [ ] ECC-VSCC
- [ ] demo golang CC ...

**Comment by mbrandenburger** [comment]
Note that MockStub moved to shimtest package, see [here](https://github.com/hyperledger/fabric-chaincode-go/blob/master/shimtest/mockstub.go). This is relevant for `utils/test_helper.go` and in mock Server.

**Comment by g2flyer** [comment]
Related to the go modules, see also #94
