### ISSUE TITLE
Remove fabric v1.4 shim logging

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-private-chaincode#248]
In many places (i.e., ERCC, TLCC, ...) we use `shim.NewLogger(...)`. This has been removed with Fabric 2.0.

For TLCC we can follow qscc and other sys chaincodes and use the following:

```
var logger = flogging.MustGetLogger("tlcc")
```

What about ECC and ERCC? Can we use this there as well or replace my simple fmt.Printf ???

**Comment by mbrandenburger** [comment]
Also used `ercc/attestation/ias.go`. Better run  grep for this shim.NewLogger

**Comment by g2flyer** [comment]
flogging looks good. Would be good though to control logging level. no SetLevel, though. Llooking at docu, i guess you have to provide a complete fabric logging spec and set it via https://godoc.org/github.com/hyperledger/fabric/common/flogging#ActivateSpec? Maybe flogging.ActivateSpec("debug") or logger.ActivateSpec("debug") might be a quick hack to get all logging?  
Note that demo/client/backend/mock/server.go has a commented out SetLevel to which above also might apply?

**Comment by mbrandenburger** [comment]
I quickly checked [Fabric samples](https://github.com/hyperledger/fabric-samples/tree/master/chaincode) and it looks like that all normal user chaincode just use `fmt.Println` instead of fancy logging.

**Comment by mbrandenburger** [comment]
I suggest 

- all our system components such as TLCC and custom validation plugins just use flogger and let the peer control it.

- user chaincodes we use `fmt.Printf`. The log level of the FPC Chaincode we control via SGX_MODE and our integrated FPC chaincode logger. See #88

**Comment by MHBauer** [comment]
1. For components built in to the peer, such as validation. I agree that we should use whatever is built in.
1. For user chaincodes, logging is now left up to the chaincode. The existing shim-logging should not be used anymore. https://hyperledger-fabric.readthedocs.io/en/release-2.0/logging-control.html#chaincode If you want to use a logger, use a logger, if not, printf is easily replaceable with a real logger later..

**Comment by g2flyer** [comment]
I think it would be nice to separate logging from (1) external shim (ecc), (2) enclave-internal shim and (3) chaincode and also give some control where to enable what.   So i don't see why would _not_ use flogging (obviously with a setup which outputs to stdout/stderr?  The fact that the sample chaincode use fmt.Printf is not a reason to not do proper logging?  does fabric-chaincode-go also just us fmt.Printf?

**Comment by mbrandenburger** [comment]
ok, using flogger is easy. See #315 how to use it in the mock server.

However, controlling it using normal user chaincodes such as ERCC it is not clear to me how we could pass FABRIC_LOGGING_SPEC to the ERCC chaincode container. However, I think this is not relevant for the concept-release-v2. We can open another issue if it's needed.

**Comment by g2flyer** [comment]
> However, controlling it using normal user chaincodes such as ERCC it is not clear to me how we could pass FABRIC_LOGGING_SPEC to the ERCC chaincode container. However, I think this is not relevant for the concept-release-v2. We can open another issue if it's needed.

I think if you read it from the environment variable it will work. If i'm not mistaken, then the peer passes on logging spec to containers ...
