### ISSUE TITLE
Launch FPC Chaincode via external builder

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#249]
This will allow a cleaner integration of fpc as a separate chaincode type and remove (mostly) the need of the peer cli wrapper.  It should also remove need of the proxy and sgx patch for the peer and the docker-switcheroo hack in the peer cli wrapper. 

Aspects on it:
- [x] identify config changes and semantics of scripts (and verify experimentally :-)
- [x] define fpc package format (presumably some structure as others, just with a new type fpc-c in the `type` field in `metadata.json`
- [ ] deployment model: 
  - [x] minimal version, running directly on host
  - [ ] initially just quick hack via plain local dockerand storing all state in the directories provided by peer to scripts
  - [ ] eventually consider moving to k8s so we can scale although this also raises some additional sgx questions ...). See also issue #401
  - [ ] support for chaincode-as-a-service mode (i.e., updating and testing `release.sh` script)
- [x] create the fpc-specific scripts `detect`, `build`, `release` and `run` with focus on normal mode and not yet CCaaS (i.e., the `release` script wouldn't really do anything ...).  This is mostly refactoring current code from `fabric/bin/peer.sh` to `build' and `run'.
- [x] change `core.yaml` and `fabric/bin/peer.sh` correspondingly to enable external builders and do packaging wrapper

Background:
- [main docu](https://hyperledger-fabric.readthedocs.io/en/release-2.0/cc_launcher.html)
- [related chaincode-as-a-service doc](https://hyperledger-fabric.readthedocs.io/en/release-2.0/cc_service.html)
- sample builders: integration/externalbuilders/golang in fabric repo

**Comment by g2flyer** [comment]
re-open as there are aspects of this feature which do not yet exist (support for CCaaS and docker/kubernetes deployment model). But removed from CC release milestone

**Comment by mbrandenburger** [comment]
#539 covers this one
