### ISSUE TITLE
Make custom-vscc for ECC and ERCC Fabric 2.0 compatible

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-private-chaincode#250]
There were rumours that plugin support has been removed from Fabric 2.0.

However, according to the [release notes](https://github.com/hyperledger/fabric/releases/tag/v2.0.0) only system chaincode plugins have been removed (FAB-15343). This does not necessary also mean custom validation plugin is dropped.

**Comment by mbrandenburger** [comment]
- Fabric 2.0 documentation still contains the custom validation plugins section, see [here](https://hyperledger-fabric.readthedocs.io/en/release-2.0/pluggable_endorsement_and_validation.html)

- Validation code still contains plugin dispatcher, see [here](https://github.com/hyperledger/fabric/blob/a282f7132565d509d3ba6d502cd9c07cc5e567f0/core/committer/txvalidator/v20/validator.go#L74)

- AND this plugin dispatcher is also called, see [here](https://github.com/hyperledger/fabric/blob/a282f7132565d509d3ba6d502cd9c07cc5e567f0/core/committer/txvalidator/v20/validator.go#L374)

**Comment by mbrandenburger** [comment]
Note that `github.com/hyperledger/fabric/protos/utils` moved to  `github.com/hyperledger/fabric/protoutil` which is used in `ercc/vscc/ercc_validation_logic.go`

**Comment by g2flyer** [comment]
maybe i'm missing something, but weren't these also go plugin with .so files and have to be called by peer?  So with plugins gone, how does the corresponding code of a specific plugin called?!

**Comment by mbrandenburger** [comment]
This issue was not yet fixed with #260

**Comment by mbrandenburger** [comment]
#322 bring all plugins (ercc-vscc, ecc-vscc, and ercc-decorator) in one single folder and builds it.

Currently, ercc-decorator works nicely with a peer, but ercc-vscc und ecc-vscc still have go dependency issues / version conflicts.
