### ISSUE TITLE
Upstream our MockCreator patch for mockstub

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#252]
fabric/0001-mock-also-creator-identity-like-signedproposal-or-Ch.patch

**Comment by g2flyer** [comment]
See also issue #246

**Comment by mbrandenburger** [comment]
I think this patch is obsolete as the new MockShim has a creator already.

-  https://github.com/hyperledger/fabric-chaincode-go/blob/master/shimtest/mockstub.go#L73
- https://github.com/hyperledger/fabric-chaincode-go/blob/master/shimtest/mockstub.go#L400

Closed thanks!
