### ISSUE TITLE
Build new Fabric v2 core utilities from script and related documentation update

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#255]
We need v2 binaries (peer, configtxgen, cryptogen, orderer) built from source for ledger created it in our integration tests (fabric/bin/lib/*, integration/*sh), see related #254

**Comment by mbrandenburger** [comment]
Fixed with #260. Fabric v2 is now available inside dev-docker and travis.

**Comment by mbrandenburger** [comment]
Fixed with #260. Fabric v2 is now available inside dev-docker and travis.
