### ISSUE TITLE
cc-builder should be based on local repo rather than on master from github

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#269]
cc-builder dockerfile depends on the fpc code checked out from dev which is master from github repo.  To make it properly work, though, it should be based on the current (local) version as done in peer.  So one way fix would be to base it on peer and "nullify" peer-specific. Given the overlap between peer and dev, we might anyway want to consolidate?

Notes: 
- cc-builder is currently disabled
- cc-builder is not on the critical path but is required to get demo running with network setup, certainly a desirable thing to have. That said, while currently added to concept release 2.0 milestone, it certainly can be dropped from that if we don't shoot for dragging the demo along with the rest of the code for now ....
- cc-build might eventually be necessary to be used for the `build` external builder script but that might anyway require some refactor ...

**Comment by mbrandenburger** [comment]
I think this issue is actually about our dev image not cc-builder :D

**Comment by mbrandenburger** [comment]
> Given the overlap between peer and dev, we might anyway want to consolidate?

would it make sense to have a "lightweight" peer image ... that just contains a fpc-custom-build peer binary and the corresponding "plugins" (as long as we still have some). This peer container does not need to build the peer itself right?

**Comment by mbrandenburger** [comment]
the dev container I would like to keep as a full fledge dev environment ... able to build FPC and run FPC chaincode using simulator (of if SGX-hardware is available even use that)

**Comment by g2flyer** [comment]
> > Given the overlap between peer and dev, we might anyway want to consolidate?
> 
> would it make sense to have a "lightweight" peer image ... that just contains a fpc-custom-build peer binary and the corresponding "plugins" (as long as we still have some). This peer container does not need to build the peer itself right?

well somebody should build it and it should be corresponding the "current" (host) code. So you definitely could split into two different images, a builder and a runner, but i'm not sure where that would simplify your life ...
