### ISSUE TITLE
Client side support: go sdk

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#289]
See also sibling features #288 and #290

**Comment by g2flyer** [comment]
We might have to wait until [FABG-928: Programming model - Add Fabric Programming Model to Go SDK](https://jira.hyperledger.org/browse/FABG-928) is closed (still in WIP as-of 2020-07-09 ..)

**Comment by bvavala** [comment]
> We might have to wait until [FABG-928: Programming model - Add Fabric Programming Model to Go SDK](https://jira.hyperledger.org/browse/FABG-928) is closed (still in WIP as-of 2020-07-09 ..)

FABG-928 is actually closed.
The Go SDK (https://github.com/hyperledger/fabric-sdk-go) seems to implement the proposed programming model on v2.1.1

**Comment by g2flyer** [comment]
> FABG-928 is actually closed.

Oops, looked at wrong status (in body it shows up as "Current Status:RFC approved. In development." ...). Anyway, good to know

**Comment by g2flyer** [comment]
BTW: chatted with morgan regarding the go client sdk issue he run into when he looked into that a while.  As far as we collectively could recollect it probably was an issue of (lack of) capability in the v1.4 compatible sdk -- at that time we didn't have yet docker-compose for 2.x, so the plan then was to start first for v1.4 ... -- and Morgan thinks 928 should address it (at least if they implemented what they claim on jira :-)
