### ISSUE TITLE
Update of UMLs following HLGF'20 discussion

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#303]
See corresponding [meeting minutes](https://docs.google.com/document/d/1ztdJykj4I-e9G-YGGnn2ExDVCQQHmbuhgdaA5HWkd9M/edit#heading=h.72b0xl56at64)

**Comment by mbrandenburger** [comment]
PR #377 updates invocation and execution diagrams based on HLFG2020 meeting notes.
