### ISSUE TITLE
Make demo work on Fabric v2

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#309]
**Description**
Ensure that demo also works in Fabric v2 in following scenarios (with decreasing priority)
- [X] mock-server with fpc cc
- [ ] fabric-gateway with fpc cc
- [x] ~~mock-server with golang cc~~
Depending on complexity, above might have to be broken down into further smaller work-items ..

**Link to dependent issues**
Issues #165, #254, #256

**Comment by mbrandenburger** [comment]
Just tested mock-server with fpc cc and it works with current master (42b34e4)

**Comment by mbrandenburger** [comment]
Just tested mock-server with go cc at least compiles but invoking create auction returned the following response:
```
No response payload received (status=500/message=json error: json: cannot unmarshal string into Go struct field Auction.owner of type golang.Principal)
```

I believe that is issue is not related to fabric v2 changes.

**Comment by mbrandenburger** [comment]
Today we decided to remove golang mock chaincode, see PR #316.

**Comment by mbrandenburger** [comment]
Once #316 is merged we will move this issue to MVP milestone.
