### ISSUE TITLE
Docker-dev is missing killall command

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-private-chaincode#314]
**Describe the bug**
The test in demo/chaincode/fpc requires `killall` command to kill the mock server after tests are finished. Our docker dev-image misses that command.

**To Reproduce**
```
cd utiles/docker
make dev; make run
cd demo/chaincode/fpc
make
```

**Expected behavior**
```
Test successful.
root@7984cc9a34dc:/project/src/github.com/hyperledger-labs/fabric-private-chaincode/demo/chaincode/fpc#
```

**Log-filesScreenshots**
```
Test successful.
./test.sh: line 11: killall: command not found
Makefile:48: recipe for target 'test' failed
make: *** [test] Error 127
root@7984cc9a34dc:/project/src/github.com/hyperledger-labs/fabric-private-chaincode/demo/chaincode/fpc#
```

**Environment (please complete the following information):**
MacOS using docker-dev images from master (42b34e4)

**Additional context**

**Comment by mbrandenburger** [comment]
installing `psmisc` fixes that issue.

I suggest to add it to dev container.

**Comment by g2flyer** [comment]
docker-compose is also missing to run fabric-network based demo. That part, though, has additional problems as volume-based mounts do not work inside the dev container as the daemon will try to find the source volumes on the host, not the dev container.   Which raises the bigger question: is the dev container a viable way for a full-scale deployment environment?  If not, we might have to add some docu on the constraints.  If it should be, we should figure out how to solve the volume mount problem ...

**Comment by mbrandenburger** [comment]
> docker-compose is also missing to run fabric-network based demo. That part, though, has additional problems as volume-based mounts do not work inside the dev container as the daemon will try to find the source volumes on the host, not the dev container. Which raises the bigger question: is the dev container a viable way for a full-scale deployment environment? If not, we might have to add some docu on the constraints. If it should be, we should figure out how to solve the volume mount problem ...

Regarding. docker compose a bigger docker refactoring is needed as discussed on our FPC meeting last week (04/21).

**Comment by g2flyer** [comment]
> Regarding. docker compose a bigger docker refactoring is needed as discussed on our FPC meeting last week (04/21).

Not clear to me that it really requires a docker-_compose_ refactoring, potentially more an issue of refactoring make targets and updates on what you run inside and/or outside of a dev-container? Anyway, definitely something for another place to solve than this PR

**Comment by g2flyer** [comment]
Also missing is `bc` ...
