### ISSUE TITLE
Convert our integration test config from solo to raft

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#317]
**Description**
Currently our integration tests (as well as docker-compose setup) relies on solo, yet solo (and kafka) are deprecated in Fabric v2, so we should upgrade to a (single-node) raft orderer.   Supposedly also should be faster ...

See PR #307 for some discussion some changes (e.g., replacing `SampleDevModeSolo` by `SampleDevModeEtcdRaft` in `common_ledger.sh`) , also will require adding tls certs for orderer (and peer/client?) See also [raft configuration docu](https://hyperledger-fabric.readthedocs.io/en/release-2.0/raft_configuration.html)

**Link to dependent issues**
Depends on #254 to be done; also related to #256

**Comment by g2flyer** [comment]
BTW: while TLS is mandatory _between_ orderer nodes, it is seems it is not necessary to communication with clients iff the client config is separatedly defined from the server config in configtx.yaml (see comments in https://github.com/APGGroeiFabriek/PIVT#scaled-up-raft-network-without-tls found via a [post in the Fabric ML](https://lists.hyperledger.org/g/fabric/topic/how_decentralized_is_the_raft/68539671?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,68539671).   Given that here we anyway want to have only one orderer node, we might get away with any client certificates which should simplify the setup.  
BTW(2): for the test setup we could potentially also create certs and keys once and for all and check them into git? Condition of course would be that life-time of certificate is long enough ....

**Comment by Jordy24** [comment]
am having a problem on polices, after switching ordertype to etcdraft in configtx.yaml and enabling tls in the orderer.yaml file, am getting an error related to policy of which I have not figured out a way to solve it.
The following is the error am getting 
`Error: got unexpected status: BAD_REQUEST -- error validating channel creation transaction for new channel 'mychannel', could not successfully apply update to template configuration: error authorizing update: error validating DeltaSet: policy for [Group]  /Channel/Application not satisfied: implicit policy evaluation failed - 0 sub-policies were satisfied, but this policy requires 1 of the 'Admins' sub-policies to be satisfied`

**Comment by bvavala** [comment]
> implicit policy evaluation failed - 0 sub-policies were satisfied, but this policy requires 1 of the 'Admins' sub-policies to be satisfied

Could you paste here the configtx and crypto-config yamls?

**Comment by Jordy24** [comment]
I guess I got a break through on the policy issue. What I did is to shutdown the docker container and then restarted it, once that was done it now was able to pass the policy stuff...

Now am hitting a timeout...

If up to this level I could just create a pr and push my changes so that you can see the all the files I have changed and others that are generated..

**Comment by Jordy24** [comment]
I have it working for now without enabling tls

**Comment by g2flyer** [comment]
As mentioned on Thursday's call, raft requires TLS _only between raft nodes_ not necessarily between raft nodes (orderer) and the clients of the ordering service.  To make it work it requires separating the communication settings (port etc ...) of these two services which are by default co-alesce. See above link i gave 5 days ago for some background ...

**Comment by g2flyer** [comment]
Addressed by PR #324
