### ISSUE TITLE
Hide ecc validation plugin with peer wrapper

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-private-chaincode#372]
**Description**

In order to use a FPC chaincode, our custom validation plugin must be used by setting it in the chaincode definition with `-V ecc-vscc` . For example:

```
${PEER_CMD} lifecycle chaincode approveformyorg -C ${CHAN_ID} --package-id ${PKG_ID} --name auction_test --version ${CC_VERS} -V ecc-vscc
```

As this may change in the future we would like to hide the use of ecc-vscc by embedding it into the peer wrapper script.

See discussion:

> Wouldn't it be better to add the validation plugin inside the peer cli?  Mid/long-term some of these plugins will change for FPC, so it would be cleaner/easier from a functional interface point of view as the interface is simpler and would be the same even if we would move to MSP/X509 style validation.  As we anyway do not allow any user-provided plugins, the peer cli of course should also barf if any plugins provided (which it currently doesn't, e.g., if you provide an endorsement plugin, which by itself is also a bit of a problem?)

_Originally posted by @g2flyer in https://github.com/hyperledger-labs/fabric-private-chaincode/pull/371_

**Link to dependent issues**
#371 re-enables custom validation plugins for ecc and ercc
#358 Management API definition  (where we should also make explicit that neither endorsement nor validation plugins are supported for FPC)

**Comment by g2flyer** [comment]
Shouldn't this be in Tech Preview milestone, not MVP? It defines the functional interface and so would be related to #358 !
