### ISSUE TITLE
MRENCLAVE as version

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#387]
**Description**

In our protocol spec and api documentation we stress that the chaincode version should be MRENCLAVE, yet all our examples use just number 0 which is a bit confusing (even though working right now).

So would be good to
1. change our scripts and example to set the version from `mrenclave` file instead of just setting it 0
1. check in `peer.sh` that version matches MRENCLAVE from package

Note that 1. we will have to do anyway at some point, so doing it now would help making the Tech Preview more realistic

**Link to feature or bug**

n/a

**Link to dependent issues**

n/a

**Comment by mbrandenburger** [comment]
I just tried to set CC_VER to mrenclave by doing the following in `integration/auction_test.sh`:

```
...
CC_PATH=${FPC_TOP_DIR}/examples/auction/_build/lib/
CC_LANG=fpc-c
CC_VER="$(cat ${CC_PATH}/mrenclave)"
...
```

Unfortunately, it seems that using base64 is not a great idea as a version number. I got the following error:
```
Error: proposal failed with status: 500 - failed to invoke backing implementation of 'ApproveChaincodeDefinitionForMyOrg': invalid chaincode version 'yAZyb3b1EyNMhEotJGnvgeaOGnp2EFzgcYpKbJhPA4Q='. Versions can only consist of alphanumerics, '_', '-', '+', and '.'
peer.sh: test failed: /project/src/github.com/hyperledger/fabric/build/bin/peer lifecycle chaincode approveformyorg -C mychannel --package-id auction_test:16e06268921fe679fa384805df553b88f8ab124efe41c3b20359e50e82491815 --name auction_test --version yAZyb3b1EyNMhEotJGnvgeaOGnp2EFzgcYpKbJhPA4Q= --signature-policy OR('SampleOrg.member') -V ecc-vscc
```

**Comment by mbrandenburger** [comment]
> 2. check in `peer.sh` that version matches MRENCLAVE from package

Not sure if this is needed. I am just wondering if an org can call `peer chaincode lifecycle approve` even without doing the package, that is, even without installing it?

**Comment by mbrandenburger** [comment]
> Unfortunately, it seems that using base64 is not a great idea as a version number. I got the following error:
> 
> ```
> Error: proposal failed with status: 500 - failed to invoke backing implementation of 'ApproveChaincodeDefinitionForMyOrg': invalid chaincode version 'yAZyb3b1EyNMhEotJGnvgeaOGnp2EFzgcYpKbJhPA4Q='. Versions can only consist of alphanumerics, '_', '-', '+', and '.'
> peer.sh: test failed: /project/src/github.com/hyperledger/fabric/build/bin/peer lifecycle chaincode approveformyorg -C mychannel --package-id auction_test:16e06268921fe679fa384805df553b88f8ab124efe41c3b20359e50e82491815 --name auction_test --version yAZyb3b1EyNMhEotJGnvgeaOGnp2EFzgcYpKbJhPA4Q= --signature-policy OR('SampleOrg.member') -V ecc-vscc
> ```

As workaround I suggest that we encode MRENCLAVE as hex string. This also aligns pretty well with Fabric has they also use hex-string encoding for hashes. See https://github.com/hyperledger/fabric/search?q=hex.DecodeString&unscoped_q=hex.DecodeString

**Comment by g2flyer** [comment]
> As workaround I suggest that we encode MRENCLAVE as hex string. This also aligns pretty well with Fabric has they also use hex-string encoding for hashes. See https://github.com/hyperledger/fabric/search?q=hex.DecodeString&unscoped_q=hex.DecodeString

Yup, good idea

**Comment by g2flyer** [comment]
> > 1. check in `peer.sh` that version matches MRENCLAVE from package
> 
> Not sure if this is needed. I am just wondering if an org can call `peer chaincode lifecycle approve` even without doing the package, that is, even without installing it?

Certainly not essentiall I think i had initially even an "ideally" in the text but then thought i shouldn't be too suggestive that we skip it outright :-).   I thought it would be a trivial one-liner.  However, thinking of it in approveformyorg you don't hat the package context directly available, so to do it you would have to add something to the bookkeeping-state (e.g., copy mrenclave file to `${FABRIC_STATE_DIR}/mrenclave.${PKG_ID}"`.  In the long run, we have to do it in ercc so maybe not worth doing it here now.   I guess from a robustness perspective right now nothing depends on the equality, so i guess it's fine to skip the check ...
