### ISSUE TITLE
Enclave creation and registration

### ISSUE THREAD

**Issue by bvavala** [hyperledger-labs/fabric-private-chaincode#404]
Implement the new FPC enclave creation and registration flow as defined [fpc-registration.puml](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/master/docs/design/fabric-v2%2B/fpc-registration.puml)

**ECC**
- [x] Implement new [ECC API](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/master/docs/design/fabric-v2%2B/interfaces.md#interface-3) 
   - [x] `initEnclave` and `ecall_init`
- [x] Lifecycle/Chaincode Invokation dispatcher in ecc (go-chaincode)
- [x] Integrate attestation API for attestation/evidence [generation](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/master/common/crypto/attestation-api/attestation/attestation.h#L13)
- [x] Use PDO crypto for enclave identity generation
- [x] ~~shim support for channel id and msp id~~

**ERCC**
- [x] Implement enclave registration related methods from [new Interface](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/master/docs/design/fabric-v2%2B/interfaces.md#interface).
- [x] Move existing validation logic from ERCC VSCC registerEnclave
- [x] Remove deprecated ERCC custom validation 
- [x] Integrate attestation API for evidence [verification](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/master/common/crypto/attestation-api/evidence/verify-evidence.h#L11)
- [x] Implement namespace scheme for [ERCC state](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/master/docs/design/fabric-v2%2B/interfaces.md#state).
- [x] Define root of trust (IAS/TLCC MRENCLAVE)
- [x] Use LSCC API to access Chaincode Definition
- [x] Ensure that only a single enclave can be registered per chaincode FOR MVP only (TBD)

**Client**
- [x] Implement new management API (Create Chaincode Enclave) in peer wrapper cli
- [x] invoke initEnclave (ECC)
- [x] grab evidence from IAS and marshal registration structure for ERCC
   - [x] attestation evidence [transformation/conversion](https://github.com/hyperledger-labs/fabric-private-chaincode/tree/master/common/crypto/attestation-api/conversion)
   - [x] integration of #412 
- [x] invoke registerEnclave (ERCC)

**Common**
- [x] protobufs for keys and evidence
- [x] Write protobuf seri/deseri code for [fpc.proto](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/master/protos/fpc/fpc.proto)
- [x] Write protobuf seri/deseri code for [attestation.proto](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/master/protos/fpc/attestation.proto)

**Comment by mbrandenburger** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enclave creation and registration](https://trello.com/c/oALDGHIL/16-enclave-creation-and-registration)
