### ISSUE TITLE
Linkable EPID credentials don't work in anything based on docker/docker-compose, e.g., demo

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#426]
**Describe the bug**

Whether epid linkable or unlinkable credentials are used are dependent on an `FPC_ATTESTATION_TYPE` env-variable.  
While we handle that properly for integration tests, we fail to propagate the variable, if defined, to the docker images which are all will be built with only support for unlinkable (the fallback if `FPC_ATTESTATION_TYPE` is undefined).

**To Reproduce**
- setup linkable credentials in `config/ias` and define `export FPC_ATTESTATION_TYPE=epid_linkable` in `./config.override.mk`
- do a `make`
- result: integration tests will pass but demo will fail

**Expected behavior**
- demo should succeed

**Log-filesScreenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by mbrandenburger** [comment]
I can confirm this issue.
