### ISSUE TITLE
make build failed in the container

### ISSUE THREAD

**Issue by DSSLab-code** [hyperledger-labs/fabric-private-chaincode#441]
make -C common build || exit;  make -C utils build || exit;  make -C ercc build || exit;  make -C ecc_enclave build || exit;  make -C ecc build || exit;  make -C tlcc_enclave build || exit;  make -C tlcc build || exit;  make -C p
lugins build || exit;  make -C fabric build || exit;  make -C examples build || exit;  make -C integration build || exit;  make -C demo build || exit;
make[1]: Entering directory '/project/src/github.com/hyperledger-labs/fabric-private-chaincode/common'
make -C crypto build || exit;
make[2]: Entering directory '/project/src/github.com/hyperledger-labs/fabric-private-chaincode/common/crypto'
Generating RSA private key, 3072 bit long modulus (2 primes)
..............................................................................++++
.............++++
e is 3 (0x03)
-- SGX_COMMON_CFLAGS: -m64 -O2
-- SGX_SDK: /opt/intel/sgxsdk
-- SGX_MODE: SIM
-- SGX_BUILD: PRERELEASE
-- SGX_LIBRARY_PATH: /opt/intel/sgxsdk/lib64
-- SGX_ENCLAVE_SIGNER: /opt/intel/sgxsdk/bin/x64/sgx_sign
-- SGX_EDGER8R: /opt/intel/sgxsdk/bin/x64/sgx_edger8r
-- SGX_SSL: /opt/intel/sgxssl
-- SGX_SSL_LIBRARY_PATH: /opt/intel/sgxssl/lib64
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:49 (ADD_SUBDIRECTORY):
  **ADD_SUBDIRECTORY given source "pdo/common/crypto" which is not an existing
  directory.**
CMake Error at CMakeLists.txt:55 (INCLUDE):
  INCLUDE could not find load file:
    pdo/common/crypto/../CMakeVariables.txt
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'openssl>=1.1.0g'
--   Found openssl, version 1.1.1
CMake Error at CMakeLists.txt:67 (ADD_SUBDIRECTORY):
  **ADD_SUBDIRECTORY given source "pdo/common/crypto/../tests/crypto" which is
  not an existing directory.**
-- Configuring incomplete, errors occurred!
See also "/project/src/github.com/hyperledger-labs/fabric-private-chaincode/common/crypto/_build/CMakeFiles/CMakeOutput.log".
Makefile:13: recipe for target '_build' failed
make[2]: *** [_build] Error 1
make[2]: Leaving directory '/project/src/github.com/hyperledger-labs/fabric-private-chaincode/common/crypto'
Makefile:11: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory '/project/src/github.com/hyperledger-labs/fabric-private-chaincode/common'
Makefile:21: recipe for target 'build' failed
make: *** [build] Error 2

Does anyone know the reason? 
I am deploying it on Google cloud with the release-2-version.
Thanks

**Comment by mbrandenburger** [comment]
Thanks for posting this! Please double check that you pulled all the submodules. By cloning FPC using the following command it should do that automatically

```
$ git clone --recursive https://github.com/hyperledger-labs/fabric-private-chaincode.git $GOPATH/src/github.com/hyperledger-labs/fabric-private-chaincode
```

Alternatively, you could also try this
```
git submodule update --init --recursive
```

I hope this helps.

**Comment by DSSLab-code** [comment]
Thanks, Marcus. It works
