### ISSUE TITLE
New IAS authentication

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#47]
IAS has a new api-key based authentication (described in revision 5.0 of IAS spec)

**Comment by mbrandenburger** [comment]
Can you please link the spec here?

**Comment by g2flyer** [comment]
> Can you please link the spec here?

no public link yet :-(

**Comment by mbrandenburger** [comment]
Closed with PR #49

**Comment by g2flyer** [comment]
> Can you please link the spec here?

finally there is a public link to v5: https://api.trustedservices.intel.com/documents/sgx-attestation-api-spec.pdf
