### ISSUE TITLE
CI fix/replacement

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#476]
**Describe the bug**

Do to some recent changes in travis by moving to a credit-based accounting system, FPCs CI doesn't work anymore as hyperledger-labs has exhausted the credits.  

There doesn't seem to be an obvious way to replenish the credits for `travis-ci.com` and `travis-ci.org`  where you still can trigger free manual builds for OSS projects, is going away at end of the year, so trying to repurpose that for our CI doesn't seem worth spending time investigating.

Given that fabric seems to use Azure Pipeline, we might have to transition to that. Technically, it probably isn't too hard judging from [Migrate from Travis to Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/migrate/from-travis?view=azure-devops) but less clear is whether there is a way to get a (for us as project) free service, e.g., by piggybacking on some existing subscriptions or alike.

**Comment by ryjones** [comment]
Hi - Hyperledger has subscriptions set up, please read out in the chat channel #ci-cd

**Comment by g2flyer** [comment]
somewhat related, dockerhub also started having limits for anonymous pulls which can make travis fail on and off.  Might require somewhere a docker registry/cache? Or configuring some docker hub credentials?

**Comment by ryjones** [comment]
GitHub also has a registry, which is free. Maybe use that?

**Comment by mbrandenburger** [comment]
I played with github actions today and tried to port our travis setup.
See https://github.com/mbrandenburger/fabric-secure-chaincode/actions

While testing I have not experienced the rate limits of docker.io; maybe gh actions uses some smart chaching?! who knows; 

Pushing our images to some registry would improve the run time of our automated tests. The challenge might be how to test changes on the images?

**Comment by g2flyer** [comment]
> I played with github actions today and tried to port our travis setup.
> See https://github.com/mbrandenburger/fabric-secure-chaincode/actions

Cool! 

> While testing I have not experienced the rate limits of docker.io; maybe gh actions uses some smart chaching?! who knows;

Would certainly make sense.  Might also help that some of the fabric images which we pull are also directly from github itself (in addition to the base ubuntu image we get from docker.io)

> Pushing our images to some registry would improve the run time of our automated tests. The challenge might be how to test changes on the images?

Completeness of test seems to me much more important than speed for CI.   So unless we have a robust idea on how to detect that nothing which an image (transitively) depends on hasn't changed, i think we should do full build.
