### ISSUE TITLE
Mitigate double initenclave/registration

### ISSUE THREAD

**Issue by bvavala** [hyperledger-labs/fabric-private-chaincode#485]
Right now the `initenclave` command/query can be issued multiple times. As a result, each execution drops the previous keys, determining the loss of the enclave identity and, most importantly, the state (encryption key).

For a discussion on why inside-the-enclave solutions do not work see [this](https://github.com/hyperledger-labs/fabric-private-chaincode/pull/482#issuecomment-740371301) and [this](https://github.com/hyperledger-labs/fabric-private-chaincode/pull/482#issuecomment-740402108) comment.

An easy mitigation can be implemented outside of the enclave in the untrusted ECC Go code.
Specifically:
1. authenticate the admin of the enclave hosting org
2. add a variable/flag to keep track of the registration

The first one is an authorization mechanism to restrict who can execute the command. As for state loss prevention (with one enclave), the org must be trusted, this is appropriate.
The second one is a convenience mechanism to prevent consecutive `initenclave` calls to succeed. It is just a convenience since the flag is ephemeral (i.e., not stored on the ledger, or any locally persistent state) and is set as long as the chaincode stays up. If chaincode, or the hosting peer, restart, it will be unset.

**Comment by g2flyer** [comment]
Double init prevented now by PR #483

**Comment by bvavala** [comment]
see here https://github.com/hyperledger-labs/fabric-private-chaincode/blob/37de010921cf28195942078c561d0bc4c0c41570/ecc/chaincode/enclave/enclave.go#L47
