### ISSUE TITLE
Hello world example for Go client SDK

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#490]
**Description**

Equivalent we have for helloworld based on cli, also for Go SDK.  Probably best done in conjunction with issue #489 as this would go for more or less identical steps.

**Link to feature or bug**

**Link to dependent issues**

**Comment by bvavala** [comment]
(per our discussions, moving this to FPC 1.1 milestone)

**Comment by mbrandenburger** [comment]
@munapower Can you please have a look at this task?
