### ISSUE TITLE
path of ias credentials is hardcoded

### ISSUE THREAD

**Issue by bvavala** [hyperledger-labs/fabric-private-chaincode#50]
possible solution:
create template of core.yaml for fabric with placemarks for ias credentials path
expand the template with environment variable set by user

**Comment by mbrandenburger** [comment]
You do mean it is hardcoded in the `core.yaml`

**Comment by bvavala** [comment]
yes.

**Comment by mbrandenburger** [comment]
Is this still a concern? I also think the title of this PR is a bit misleading as it says hardcoded, which I think refers to hardcoded-in-code-somethere, whereas `core.yaml` actually points to `ias/api_key.txt`.

Closed for now. If still an issue we can reopen.
