### ISSUE TITLE
FPC 1.0 Release finalization

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#510]
**Description**

Steps to be done:
- [x] create branch `release-1.0` (as in fabric, pointing to major.minor , excluding debug level, with future debug releases 1.0.x also pushed onto this branch!)
- [x] create commit with
  - [x] in `config.mk` change `FPC_VERSION` from `master` to `v1.0.0` (i.e., fully qualified semantic version including debug level)
  - [x] in `README.md` add item to the release section (maybe also add to that section a link to `https://github.com/hyperledger-labs/fabric-private-chaincode/releases` as a substitute of the missing `CHANGELOG` ?)
  - [x] replace all github source references mentioning  `master` in docu  to equivalent `release-1.0` (i.e., referencing branch and minor version, not tag and debug version!); find files via ` egrep -r 'https://github.com/hyperledger-labs/fabric-private-chaincode/blob/master'` ...
- [x] on [github](https://github.com/hyperledger-labs/fabric-private-chaincode/releases) create new release with tag `v1.0.0` and description pointing out first e2e secure version, reference to RFC, etc etc
- [x] announce on rocket chat & Fabric mailing list

**Link to feature or bug**

**Link to dependent issues**

Obviously relies on all other issues from [FPC 1.0 milestone](https://github.com/hyperledger-labs/fabric-private-chaincode/milestone/38) closed or moved to later milestones

**Comment by bvavala** [comment]
The release was actually renamed to 1.0-RC1, in order to keep the 1.0 version for when FPC joins an official Fabric repo.
Tasks have been completed.
