### ISSUE TITLE
make build failed

### ISSUE THREAD

**Issue by lubaolalala** [hyperledger-labs/fabric-private-chaincode#514]
`Step 17/21 : RUN  go get golang.org/x/tools/cmd/goimports   && go get google.golang.org/protobuf/cmd/protoc-gen-go   && GO111MODULE=off go get github.com/maxbrunsfeld/counterfeiter
 ---> Running in e7caf029ea10
package golang.org/x/tools/cmd/goimports: unrecognized import path "golang.org/x/tools/cmd/goimports": https fetch: Get "https://golang.org/x/tools/cmd/goimports?go-get=1": dial tcp 216.239.37.1:443: i/o timeout
The command '/bin/sh -c go get golang.org/x/tools/cmd/goimports   && go get google.golang.org/protobuf/cmd/protoc-gen-go   && GO111MODULE=off go get github.com/maxbrunsfeld/counterfeiter' returned a non-zero code: 1
make[2]: *** [Makefile:162: base-dev] Error 1
make[2]: Leaving directory '/home/luabolalala/go/src/github.com/hyperledger-labs/fabric-private-chaincode/utils/docker'
make[1]: *** [Makefile:11: build] Error 2
make[1]: Leaving directory '/home/luabolalala/go/src/github.com/hyperledger-labs/fabric-private-chaincode/utils'
make: *** [Makefile:22: build] Error 2
`
I've struggled with the problem for many days. I would be appreciative if you could help me solve it.

**Comment by g2flyer** [comment]
My first suspicion is that you might be behind a proxy and didn't configure docker properly or just have a very slow network connection (the go get pulls in quite some dependency and takes a bit of time).   That said, to help you better, could you please fill out below template (which is what you would have got iff you selected the bug template when creating an issue ..).  Primarily the steps to reproduce and the environment is important. Also if you could attach the complete log-file from make also might help ...

**Describe the bug**
<--! 
  Add a clear and concise description of what the bug is. 
-->

**To Reproduce**
<--! 
Add steps to reproduce the behavior, e.g.
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
-->

**Expected behavior**
<--! 
  Add a clear and concise description of what you expected to happen. 
-->

**Log-filesScreenshots**
<--! 
 If applicable, add screenshots to help explain your problem. 
-->

**Environment (please complete the following information):**


**Additional context**
<--!
  Add any other context about the problem here.
-->

**Comment by lubaolalala** [comment]
**Describe the bug**
when I run the command `make`,it shows that `Step 17/21 : RUN  go get golang.org/x/tools/cmd/goimports   && go get google.golang.org/protobuf/cmd/protoc-gen-go   && GO111MODULE=off go get github.com/maxbrunsfeld/counterfeiter
` couldn't correctly run.

**To Reproduce**
```
cd fabric-private-chaincode
make
```

**Expected behavior**

**Log-filesScreenshots**
`Step 14/21 : ENV GOROOT=/usr/local/go
 ---> Using cache
 ---> 3df63d737fc1
Step 15/21 : RUN GO_TAR=go${GO_VERSION}.linux-amd64.tar.gz   && wget -q https://dl.google.com/go/${GO_TAR}   && tar -xf ${GO_TAR}   && mv go /usr/local   && rm ${GO_TAR}   && mkdir -p /project
 ---> Using cache
 ---> 13b3be17b020
Step 16/21 : ENV PATH=${GOPATH}/bin:${GOROOT}/bin:${PATH}
 ---> Using cache
 ---> f7d7027fdf8f
Step 17/21 : RUN  go get golang.org/x/tools/cmd/goimports   && go get google.golang.org/protobuf/cmd/protoc-gen-go   && GO111MODULE=off go get github.com/maxbrunsfeld/counterfeiter
 ---> Running in 0b6d1bfc7f71
package golang.org/x/tools/cmd/goimports: unrecognized import path "golang.org/x/tools/cmd/goimports": https fetch: Get "https://golang.org/x/tools/cmd/goimports?go-get=1": proxyconnect tcp: dial tcp 127.0.0.1:12333: connect: connection refused
The command '/bin/sh -c go get golang.org/x/tools/cmd/goimports   && go get google.golang.org/protobuf/cmd/protoc-gen-go   && GO111MODULE=off go get github.com/maxbrunsfeld/counterfeiter' returned a non-zero code: 1
make[2]: *** [Makefile:162: base-dev] Error 1
make[2]: Leaving directory '/home/luabolalala/go/src/github.com/hyperledger-labs/fabric-private-chaincode/utils/docker'
make[1]: *** [Makefile:11: build] Error 2
make[1]: Leaving directory '/home/luabolalala/go/src/github.com/hyperledger-labs/fabric-private-chaincode/utils'
make: *** [Makefile:22: build] Error 2
`

**Environment**
Ubuntu 20.04
FPC the newest version
hyperledger fabricv2.2.0
docker 19.03.9

Additional context
It seems like I didn't set the proxy.Therefore I followed the description of working from behind a proxy.But it showed connetction refused.But the proxy doesn't exsit problems.

**Comment by lubaolalala** [comment]
> 我的第一个怀疑是您可能在代理后面，未正确配置docker或网络连接速度非常慢（go get引入了相当大的依赖关系，并花费了一些时间）。就是说，为了更好地帮助您，请您填写下面的模板（如果您在创建问题时选择了错误模板，就会得到此信息）。首先，繁殖的步骤和环境很重要。另外，如果您可以附加make的完整日志文件，也可能会有所帮助...
> 
> **描述错误**
> <-
> 添加清晰明确的错误说明。
> ->
> 
> **重现**
> <-
> 添加重现行为的步骤，例如
> 
> 1. 去 '...'
> 2. 点击 '....'
> 3. 向下滚动到“ ....”
> 4. 看到错误
>    ->
> 
> **预期行为**
> <-
> 添加对您期望发生的事情的简洁明了的描述。
> ->
> 
> **日志文件** 屏幕截图
> <-
> 如果适用，请添加屏幕截图以帮助解释您的问题。
> ->
> 
> **环境（请填写以下信息）**
> <-
> 
> * 操作系统（发行版+版本）：[例如Ubuntu 18.04]
> * FPC版本（标签或提交ID）[例如'concept-release'] 
>   ->
> 
> **其他上下文**
> <-
> 在此处添加有关该问题的任何其他上下文。
> ->

**Describe the bug**
when I run the command `make`,it shows that `Step 17/21 : RUN go get golang.org/x/tools/cmd/goimports && go get google.golang.org/protobuf/cmd/protoc-gen-go && GO111MODULE=off go get github.com/maxbrunsfeld/counterfeiter` couldn't correctly run.(timeout or connection refused)

**To Reproduce**

```
cd fabric-private-chaincode
make
```
**Log-filesScreenshots**
```
Step 14/21 : ENV GOROOT=/usr/local/go 
---> Using cache 
---> 3df63d737fc1 
Step 15/21 : RUN GO_TAR=go${GO_VERSION}.linux-amd64.tar.gz && wget -q https://dl.google.com/go/${GO_TAR} && tar -xf ${GO_TAR} && mv go /usr/local && rm ${GO_TAR} && mkdir -p /project 
---> Using cache 
---> 13b3be17b020 
Step 16/21 : ENV PATH=${GOPATH}/bin:${GOROOT}/bin:${PATH} 
---> Using cache 
---> f7d7027fdf8f 
Step 17/21 : RUN go get golang.org/x/tools/cmd/goimports && go get google.golang.org/protobuf/cmd/protoc-gen-go && GO111MODULE=off go get github.com/maxbrunsfeld/counterfeiter 
---> Running in 0b6d1bfc7f71 
_package golang.org/x/tools/cmd/goimports: unrecognized import path "golang.org/x/tools/cmd/goimports": https fetch: Get "https://golang.org/x/tools/cmd/goimports?go-get=1": proxyconnect tcp: dial tcp 127.0.0.1:12333: connect: connection refused_ 
The command '/bin/sh -c go get golang.org/x/tools/cmd/goimports && go get google.golang.org/protobuf/cmd/protoc-gen-go && GO111MODULE=off go get github.com/maxbrunsfeld/counterfeiter' returned a non-zero code: 1 
make[2]: *** [Makefile:162: base-dev] Error 1 
make[2]: Leaving directory '/home/luabolalala/go/src/github.com/hyperledger-labs/fabric-private-chaincode/utils/docker' 
make[1]: *** [Makefile:11: build] Error 2 
make[1]: Leaving directory '/home/luabolalala/go/src/github.com/hyperledger-labs/fabric-private-chaincode/utils' 
make: *** [Makefile:22: build] Error 2
```

**Environment**
Ubuntu 20.04
FPC the newest version
hyperledger fabric v2.2.0
docker 19.03.9

**Additional context**
It seems like I didn't set the proxy.Therefore I followed the description of working from behind a proxy.But it showed connetction refused.But the proxy doesn't exist problems.

**Comment by lubaolalala** [comment]
**Describe the bug**
when I run the command `make`,it shows that `Step 17/21 : RUN go get golang.org/x/tools/cmd/goimports && go get google.golang.org/protobuf/cmd/protoc-gen-go && GO111MODULE=off go get github.com/maxbrunsfeld/counterfeiter` couldn't correctly run.(timeout or connection refused)

**To Reproduce**
```
cd fabric-private-chaincode
make
```

**Log-filesScreenshots**

```
Step 14/21 : ENV GOROOT=/usr/local/go 
---> Using cache 
---> 3df63d737fc1 
Step 15/21 : RUN GO_TAR=go${GO_VERSION}.linux-amd64.tar.gz && wget -q https://dl.google.com/go/${GO_TAR} && tar -xf ${GO_TAR} && mv go /usr/local && rm ${GO_TAR} && mkdir -p /project 
---> Using cache 
---> 13b3be17b020 
Step 16/21 : ENV PATH=${GOPATH}/bin:${GOROOT}/bin:${PATH} 
---> Using cache 
---> f7d7027fdf8f 
Step 17/21 : RUN go get golang.org/x/tools/cmd/goimports && go get google.golang.org/protobuf/cmd/protoc-gen-go && GO111MODULE=off go get github.com/maxbrunsfeld/counterfeiter 
---> Running in 0b6d1bfc7f71 
_package golang.org/x/tools/cmd/goimports: unrecognized import path "golang.org/x/tools/cmd/goimports": https fetch: Get "https://golang.org/x/tools/cmd/goimports?go-get=1": proxyconnect tcp: dial tcp 127.0.0.1:12333: connect: connection refused_ 
The command '/bin/sh -c go get golang.org/x/tools/cmd/goimports && go get google.golang.org/protobuf/cmd/protoc-gen-go && GO111MODULE=off go get github.com/maxbrunsfeld/counterfeiter' returned a non-zero code: 1 
make[2]: *** [Makefile:162: base-dev] Error 1 
make[2]: Leaving directory '/home/luabolalala/go/src/github.com/hyperledger-labs/fabric-private-chaincode/utils/docker' 
make[1]: *** [Makefile:11: build] Error 2 
make[1]: Leaving directory '/home/luabolalala/go/src/github.com/hyperledger-labs/fabric-private-chaincode/utils' 
make: *** [Makefile:22: build] Error 2
```

**Environment**
Ubuntu 20.04
FPC the newest version
hyperledger fabric v2.2.0
docker 19.03.9
docker-compose 1.25.0-rc1

**Additional context**
It seems like I didn't set the proxy.Therefore I followed the description of working from behind a proxy.But it showed connetction refused.But the proxy doesn't exist problems.

**Comment by g2flyer** [comment]
Hmm, Ubuntu 20.04 is not officially supported (and should actually fail with the recommended SGX version!).  There is a current open PR (#509) which should improve on this, though.  Not that your problem seems related to this, though.  If you don't use a proxy, then i have no other good idea why it fails for you. If you really run `make` from FPC top-level then a `go get` for goimports must have succeeded on your host and it just fails inside a docker build.  So something with your docker setup must seem broken.

BTW: also note that as the `README.md` states, `master` is not a recommended version on would be better to start with Concept Release 2.0 (i.e., branch `concept-release-2.0` and/or tag `cr2.0.0`).

**Comment by lubaolalala** [comment]
Thank you for solving my problems! I will check my docker setup , and try your suggestions.

**Comment by mbrandenburger** [comment]
Let's close this one. Please feel free to re-open if there is still an issue. Thanks
