### ISSUE TITLE
Snap upgrades to new incompatible version of yq

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#519]
**Describe the bug**

If you installed yq via snap, you might get since recently following error when running `setup.sh` in test-network:
```
msteiner@sgxnuc2 ~/.../hyperledger-labs/fabric-private-chaincode/integration/test-network (concept-release-2.0 *=)$ ./setup.sh
Error: unknown command "m" for "yq"
```
This is as `snap` did update the (default) latest version from v3 to v4.

If you explicitly subscribe to v3 via 
```
snap switch yq --channel v3/stable
snap refresh
```
it should work again.  

**To Reproduce**

Follow README's instruction with snap install and run `setup.sh` ...

**Expected behavior**

It should not fail :-)

**Log-filesScreenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by mbrandenburger** [comment]
Same issue on a mac.

Installing yq v3 helps to run our test-network on a Mac (but build FPC components inside dev container)

```
brew install yq@3
```

**Comment by g2flyer** [comment]
Note that for docker (and hence, e.g., `dev` container) we install `yq` directly from source and explicitly as v3, so there is no issue there  (but if ever we are going to upgrade our scripts using yq to use v4+, we shouldn't forget to also upgrade docker, not only scripts and README ...)
