### ISSUE TITLE
Make logging consumable ...

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#53]
- more dev-friendly logging in sgxconfig/core.yaml
      - core.yaml vm->docker->attachStdout = true to get output in peer
      - core.yaml chaincode->logging->level = debug
      - core.yaml chaincode->logging->shim = info

- peer add default definition (if not yet defined) of FABRIC_LOGGING_SPEC to a meaningful default, e.g., vscc,ltcc,tl-encalve=DEBUG:comm.grpc=ERROR:INFO

- some reference to logging config in README

- more long term:
  - replace printf in edl with log-function which has levels so we so C levels also in Go
  - separate in enclave shim log the namespace for user-chaincode log statements from log-statements by the FPC runtime (shim)

**Comment by mbrandenburger** [comment]
I also suggest that we set `SGX_BUILD` to DEBUG by default as this may simplify our life developing.
