### ISSUE TITLE
FPC 1.0 RC1

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-private-chaincode#534]
**Description**

Steps to be done:
- [x] create branch `v1.0-rc1`
- [x] create commit with
  - [x] in `config.mk` change `FPC_VERSION` from `master` to `v1.0-rc1`
  - [x] in `README.md` add item to the release section 
  - [x] replace all github source references mentioning  `master` in docu  to equivalent `v1.0-rc1` version (find files via ` egrep -r 'https://github.com/hyperledger-labs/fabric-private-chaincode/blob/master'`)
- [x] on [github](https://github.com/hyperledger-labs/fabric-private-chaincode/releases) create new release with tag `v1.0-rc1` and description pointing out first e2e secure version, reference to RFC, etc etc
- [x] announce on rocket chat & Fabric mailing list

**Link to feature or bug**

**Link to dependent issues**

Obviously relies on all other issues from [FPC 1.0 milestone](https://github.com/hyperledger-labs/fabric-private-chaincode/milestone/38) closed or moved to later milestones

**Comment by bvavala** [comment]
release completed and announced
