### ISSUE TITLE
Initial Readme and HelloWorld Example with documentation errors

### ISSUE THREAD

**Issue by munapower** [hyperledger-labs/fabric-private-chaincode#536]
**Describe the bug**
Following the readme's there are missing statements both in the general readme as well as the HelloWorld example that do not allow the end user to finish successfully. 

**To Reproduce**
In the initial readme if the user chooses to use the docker image provided there is no suggestion / instruction on how the repository should have been cloned. If -recursive is not included in the git clone and they follow on to do the HelloWorld example they will not have the complete fabric repositories and will not be able to execute the test.

Following the HelloWorld Example the excerpt of the invoke method contains the following line:
LOG_DEBUG("HelloworldCC: \tArgs: %s", args);
that should not be there or commented, otherwise when compiled it raises an error.
The test.sh script is missing definitions and the commands are missing arguments. CC_SEQ (sequence) should be defined and then:
try ${PEER_CMD} lifecycle chaincode approveformyorg -C ${CHAN_ID} --package-id ${PKG_ID} --name ${CC_ID} --version ${CC_VER} --signature-policy ${CC_EP}
    try ${PEER_CMD} lifecycle chaincode commit -C ${CHAN_ID} --name ${CC_ID} --version ${CC_VER} --signature-policy ${CC_EP}
are missing sequence and ORDERER ADDRESS arguments

    try ${PEER_CMD} lifecycle chaincode checkcommitreadiness -C ${CHAN_ID} --name ${CC_ID} --version ${CC_VER} --signature-policy ${CC_EP}  is missing sequence argument

 try ${PEER_CMD} lifecycle chaincode initEnclave --name ${CC_ID} is missing ORDERER and PEER ADDRESS arguments

**Expected behavior**
End user should have been able to follow along readmes without any mishaps.

**Log-filesScreenshots**

**Environment (please complete the following information):**
 - OS (distro+version): docker image Ubuntu 18
 - FPC Version (tag or commit-id) 

**Additional context**

**Comment by mbrandenburger** [comment]
@munapower thanks for reporting this! this is really helpful! Do you want to create a PR to fix the identified issues? Happy to review and help to improve.

**Comment by munapower** [comment]
Hello Marcus! I followed your guidelines and forked the repository and have already changed both readmes. I was waiting for our meeting today to see if I should commit them or not ...

Saludos,
Maria Munaro
Sent from my iPhone

On 9 Feb 2021, at 05:54, Marcus Brandenburger <notifications@github.com> wrote:

﻿

@munapower<https://github.com/munapower> thanks for reporting this! this is really helpful! Do you want to create a PR to fix the identified issues? Happy to review and help to improve.
