### ISSUE TITLE
need help for run sample in integration/test-network/

### ISSUE THREAD

**Issue by TrueAbc** [hyperledger-labs/fabric-private-chaincode#544]
I have followed readme for integration/test-network and started  FPC Container like this.

![image](https://user-images.githubusercontent.com/47651330/111955570-a350d800-8b24-11eb-94fc-f2b255d023b2.png)

Then I want to  interact interactively with the peer, but when I want to get public key of echo_ecc from ercc. I
got "no suck key" error. 

![image](https://user-images.githubusercontent.com/47651330/111955459-7bfa0b00-8b24-11eb-8c63-29a960869b17.png)

It seems that ecc container works well.
![image](https://user-images.githubusercontent.com/47651330/111957208-a9e04f00-8b26-11eb-9dc7-ff9a6572d0af.png)

I just found nothing except waring message like this in docker log.
![image](https://user-images.githubusercontent.com/47651330/111956185-705b1400-8b25-11eb-9512-49aaec20d694.png)

Does anyone know how to fix the problem? Thanks a lot.

**Comment by mbrandenburger** [comment]
Hi, did you init the enclave using [LifecycleInitEnclave](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/master/client_sdk/go/pkg/client/resmgmt/lifecycleclient.go)  after running `make ercc-ecc-start`?

Background: Once you run `make ercc-ecc-start`, the FPC Enclave Registry (ercc) and your FPC Chaincode container are spawn, but no enclave has been created and registered at ercc yet. This is the reason why you don't get the public key for echo_ecc from ercc.

**Comment by mbrandenburger** [comment]
Oh I just realized that `${FPC_PATH}/client_sdk/go/sample` does not call `LifecycleInitEnclave`. Thus, I assume that this sample won't work out-of-the-box with the network you are just setting up.

**Comment by TrueAbc** [comment]
Thanks for your advice. I have run this test program successfully after adding LifecycleInitEnclave call in sample program.
![image](https://user-images.githubusercontent.com/47651330/112295517-f1a1da80-8cce-11eb-9d33-6aafc3860b78.png)

**Comment by TrueAbc** [comment]
And I wanna know if demo program in [branch concept-release-2.0 ](https://github.com/hyperledger-labs/fabric-private-chaincode/tree/concept-release-2.0/demo) still worth reading for a beginner to FPC framework. I noticed this demo is much more complete. But I don't know if it's compatible with current version of FPC.

**Comment by mbrandenburger** [comment]
> And I wanna know if demo program in [branch concept-release-2.0 ](https://github.com/hyperledger-labs/fabric-private-chaincode/tree/concept-release-2.0/demo) still worth reading for a beginner to FPC framework. I noticed this demo is much more complete. But I don't know if it's compatible with current version of FPC.

I think the FPC auction chaincode in the Demo is the most advanced example we currently have for FPC. Unfortunately, it is not compatible with the current version of FPC. For the following reasons:

- The demo does not use our go client sdk
- The auction demo requires the use of the Trusted Ledger Enclave (TLCC) to verify that ledger state is actually committed to the ledger. Without the TLCC, there is the risk of rollback attacks against the chaincode enclave, which may break the confidentiality of an auction. We elaborate on this topic in our paper, which you can find in the README.

Anyway, looking at the code of the FPC auction demo will still give you a good example how to write "more complex" applications with FPC - just keep in mind that this particular use case requires the TLCC component which we currently don't have. Thinking of it - maybe with some code changes, the FPC auction demo can also be realized with the current FPC version. We certainly would like to bring it back in the future in some form.

**Comment by mbrandenburger** [comment]
> Thanks for your advice. I have run this test program successfully after adding LifecycleInitEnclave call in sample program.

The reason why I removed the `LifecycleInitEnclave` from the sample is, that we also use the program in out integration test. However, in the integration test, `LifecycleInitEnclave` is called by the test harness. 

I think it would be nice to add a small sample application just for `LifecycleInitEnclave`, which then can be used together with the sample network tutorial. I think if your code changes to the sample program are refactored into a separate app, this would be pretty simple.

I would like to encourage you to share this with the FPC community and create a PR. WDYT? :D

**Comment by TrueAbc** [comment]
I just add a function call here and recover panice so that it won't crash sample program.
Here is the code I added.
```golang
	gw, err := gateway.Connect(
		gateway.WithConfig(config.FromFile(filepath.Clean(ccpPath))),
		gateway.WithIdentity(wallet, "appUser"),
	)

	func(){
		defer func() {
			err:=recover()
			if err!=nil {
				fmt.Println(err)
			}
		}()
		sdk, err := fabsdk.New(config.FromFile(filepath.Clean(ccpPath)))
		if err != nil {
			fmt.Println("failed to create sdk: ", err)
			return
		}
		defer sdk.Close()


		orgAdmin := "Admin"
		orgName := "org1"
		adminContext := sdk.Context(fabsdk.WithUser(orgAdmin), fabsdk.WithOrg(orgName))

		client, err := fpcmgmt.New(adminContext)
		if err != nil {
			fmt.Println("failed to create context: ", err, client)
			return
		}
		attestationParams, err := sgx.CreateAttestationParamsFromEnvironment()
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(ccID)
		initReq := resmgmt.LifecycleInitEnclaveRequest{
			ChaincodeID:         ccID,
			EnclavePeerEndpoint: "peer0.org1.example.com", // define the peer where we wanna init our enclave
			AttestationParams:   attestationParams,
		}
		fmt.Println("starting enclave init")
		initTxId, err := client.LifecycleInitEnclave("mychannel", initReq)
		if err != nil {
			fmt.Println(err)
		}
		fmt.Println(initTxId)
	}()

	if err != nil {
		logger.Fatalf("Failed to connect to gateway: %v", err)
	}
```

connection-org1.yaml file which is automatically generated by network.sh lacks some configuration.And to manage chaincode lifecycle I just add configurations manually(including organizations.Org1.cryptoPath,  organizations.Org1.users.Admin,  and channels).

![image](https://user-images.githubusercontent.com/47651330/112408203-5c482a00-8d52-11eb-8ed0-072051caae1f.png)
![image](https://user-images.githubusercontent.com/47651330/112409097-d88f3d00-8d53-11eb-88f7-280c787c22c3.png)

So I think how to add necessary configurations to connection.yaml should be considered before adding LifecycleInitEnclave Call in Sample
![image](https://user-images.githubusercontent.com/47651330/112409204-0a080880-8d54-11eb-9034-3771f16a0e29.png)

**Comment by mbrandenburger** [comment]
oh you are right, we need to modify the connection yamls to support the low-level go sdk functions. 

We could modify `ccp-template.json/yaml` via our `setup.sh` and add the missing configurations. When the `network.sh` generate the connection profiles, everything should be there. The clean way would be to create a 
proper PR on fabric-sample repo, but I think for FPC we can do it here quick and dirty. WDYT?

**Comment by TrueAbc** [comment]
I'm not familiar with shell script.So If it's easy to modify yaml/json configurations using setup.sh, I prefer  doing it in FPC repo. Or maybe you could add notes in readme.md so that beginner could fix this manually.

**Comment by mbrandenburger** [comment]
Let me reopen this since we need to update the documentation by adding the missing steps.

**Comment by TrueAbc** [comment]
I just write a python3 script to add missing conection config using ruamel library. 
Before the documentation is updated,  those who meet this problem can refer to my script.
```python3
from ruamel import yaml
import os

env_dist = os.environ
FPC_PATH = env_dist["FPC_PATH"]
print(FPC_PATH)
base_path = os.path.join(
    FPC_PATH, "integration",
    "test-network", "fabric-samples",
    "test-network", "organizations",
    "peerOrganizations"
)

org1Path = os.path.join(
    base_path,
    "org1.example.com",
)

org2Path = os.path.join(
    base_path,
    "org2.example.com"
)

def addOrg(orgpath, Org):
    Org = Org.lower()
    connection = os.path.join(orgpath, "connection-{}.yaml".format(Org))
    with open(connection, encoding='utf-8') as f:
        config = yaml.safe_load(f)

        print("adding channel concig to connection.yaml")
        ChannelConfig(config, Org)
        print("adding user config to connection.yaml")
        AdminConfig(config, orgpath, Org)


        with open(os.path.join(orgpath, "copy.yaml"), "w", encoding='utf-8') as cf:
            yaml.dump(config, cf, Dumper=yaml.RoundTripDumper)

def ChannelConfig(config, orgname):
    orgname = orgname.lower()
    peers = {"peer0.{}.example.com".format(orgname): {"endorsingPeer": True,
                                        "chaincodeQuery": True,
                                        "ledgerQuery": True,
                                        "eventSource": True}}
    config["channels"] = {"mychannel": {"peers": peers} }

def AdminConfig(config, orgPath, orgname):
    certpath = os.path.join(orgPath, "users", "Admin@{}.example.com".format(orgname), "msp")
    config["organizations"][orgname.capitalize()]["cryptoPath"] = certpath
    certname = os.listdir(
        os.path.join(certpath,
                     "signcerts")
    )[0]
    # this dir exists only one file
    keypath = os.listdir(
        os.path.join(
            certpath, "keystore"
        )
    )[0]
    admin = {"cert": {"path": os.path.join(
        certpath, "signcerts", certname
    )}, "key": {"path": os.path.join(
        certpath, "keystore", keypath
    )}}
    config["organizations"][orgname.capitalize()]["users"] = {"Admin": admin}

if __name__ == "__main__":
    # org name is org1 or org2
    addOrg(org1Path, "org1")
    addOrg(org2Path, "org2")
```

**Comment by mbrandenburger** [comment]
> Before the documentation is updated, those who meet this problem can refer to my script.

Can you please have a look at PR #553 and see if this resolves the issues you have encountered?
