### ISSUE TITLE
where to find log info

### ISSUE THREAD

**Issue by TrueAbc** [hyperledger-labs/fabric-private-chaincode#550]
![image](https://user-images.githubusercontent.com/47651330/112721038-c02e4680-8f3c-11eb-9a65-d319d9f523ea.png)

![image](https://user-images.githubusercontent.com/47651330/112721094-02f01e80-8f3d-11eb-8938-fd987b15ca50.png)
I just set ```SGX_BUILD=DEBUG```, but i can't find debug log of my chaincode in ```/tmp/hyperledger/test/peer.err``` after running
helloworld test in [tutorial](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/master/examples/README.md).
So I want to know if I ignore some information about log function or if it's possible to redirect log file path.

![image](https://user-images.githubusercontent.com/47651330/112721124-2d41dc00-8f3d-11eb-9100-f8295cf4fb76.png)

**Comment by mbrandenburger** [comment]
oh - this part of the tutorial needs to be updated! 

Before we used the external Builder, the logging of the enclave was indeed routed to the `peer.err`. However, using external Builders, all logging is piped into it's own file.

Please check your `/tmp` folder. The external builder creates output the logs into the following file `/tmp/fpc-extbuilder.${date_time}.${chaincode_name}/chaincode.log`

Also make sure you that you rebuild `common/logging/` and `examples/helloworld` after setting `SGX_MODE=DEBUG`.

**Comment by TrueAbc** [comment]
I have set ```SGX_MODE=DEBUG```. And I found log file in ```/tmp/fpc-extbuilder.${date_time}.${chaincode_name}/chaincode.log```. Thanks a lot.

![image](https://user-images.githubusercontent.com/47651330/112739942-2c479380-8fab-11eb-8aa2-59e9a75cd992.png)

**Comment by mbrandenburger** [comment]
Note that my comment above had a mistake. To enable FPC chaincode logging you need to set `SGX_BUILD=DEBUG`. `SGX_MODE` allows you to control the use of SGX simulation / hardware mode.
