### ISSUE TITLE
Better repo structure for FPC examples

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-private-chaincode#555]
**Description**

As identified in a discussion in #539, the current repo structure lacks of a central place for FPC examples.

As mentioned by @bvavala:
> as we are adding FPC applications/tests, I am noticing that we are fragmenting tests and examples among the integration, examples and, more recently, client_sdk folder. Is there a better way to architect the code/repo?

Let me propose the following structure.
- `$FPC_PATH/examples/chaincode`
- `$FPC_PATH/examples/application`
- `$FPC_PATH/examples/deployment`
- `$FPC_PATH/examples/demos`

We move all our example chaincodes current located in `examples` to `$FPC_PATH/examples/chaincode`. The client sdk samples in `client_sdk/go/sample/` move into `$FPC_PATH/examples/application`, and the k8s tutorial as well as the test-network tutorial, currently located in `$FPC_PATH/integration`, move to `$FPC_PATH/examples/deployment`.

In `$FPC_PATH/examples/demos` we could place more advanced examples like our spectrum auction comprising chaincodes, applications, and deployments.

Also note that the examples in `$FPC_PATH/examples/deployment` should only depend on existing chaincodes and applications.

This new structure with a central folder for all examples and tutorials will enhance FPC users experience.

@bvavala WDYT?

**Comment by bvavala** [comment]
Definitely a step in the right direction.

Two considerations:
* the term "applications" was not immediately clear. In fact, that's the client. So how about "clients", "client-apps", "cc-clients" or "chaincode-clients"? (I think I prefer the last one)
* good to have deployments depend only on existing examples, so we should include the helloworld in there, right?

**Comment by mbrandenburger** [comment]
> the term "applications" was not immediately clear. In fact, that's the client. So how about "clients", "client-apps", "cc-clients" or "chaincode-clients"? (I think I prefer the last one)

I proposed "applications" since this is also the name used in the fabric-samples repo. See an example here https://github.com/hyperledger/fabric-samples/tree/main/asset-transfer-basic 

In the fabric-samples repo, however, they structure the examples based on the use case (including application (client app) and chaincode). Still, I think for FPC, the structure proposed above still makes more sense.

> good to have deployments depend only on existing examples, so we should include the helloworld in there, right?

Agree, all demos/deployments should use existing examples. The latest change in #539 replaced helloworld with the echo chaincode. So we are good here

**Comment by mbrandenburger** [comment]
Note while working on this PR I choose `samples` over `examples`
