### ISSUE TITLE
how to get ledger data in enclave chaincode.

### ISSUE THREAD

**Issue by TrueAbc** [hyperledger-labs/fabric-private-chaincode#558]
Can FPC developer get local ledger or block data?  I noticed that shim.h in this release(v1.0-rc1
) only expose interface to contact with world state  DB. 
Or if it's possible to get transaction data from  shim_ctx_ptr_t ctx and just put data into world state DB?

**Comment by bvavala** [comment]
> how to get ledger data in enclave chaincode

For this purpose, the FPC shim exposes the `get_state` function, which ends up calling the `GetState` function in the Fabric shim.

> Can FPC developer get local ledger or block data? I noticed that shim.h in this release(v1.0-rc1) only expose interface to contact with world state DB. 

For the moment there's no notion of "local" or "block" data for FPC chaincodes. An FPC chaincode can only read/write key-value pair to/from its own namespace/world-state.

> Or if it's possible to get transaction data from shim_ctx_ptr_t ctx and just put data into world state DB?

An FPC chaincode can get the cleartext transaction data, as it was sent by the client through the [EvaluateTransaction](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/7897b83943fe7a21241b86426e521a57d01893c0/integration/client_sdk/go/auction_test.go#L182) (if using the FPC client sdk) or the [fpc-peer chaincode invoke](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/e73601549aa49a1eeb01562a4d7bd0e79ba04b04/integration/auction_test.sh#L52) (if using the FPC CLI).
Inside the FPC chaincode, this can be achieved through the [`get_func_and_params`](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/ad1b5d141b118708674939ea2af26ee4f3edfba5/docs/design/fabric-v2%2B/interfaces.md). See an example [here](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/7b3079cfaa1d7aadd08b623cf243db37d2329be5/examples/auction/auction_cc.cpp#L66).
