### ISSUE TITLE
how to update key-value pairs using put_state

### ISSUE THREAD

**Issue by TrueAbc** [hyperledger-labs/fabric-private-chaincode#559]
![image](https://user-images.githubusercontent.com/47651330/113555855-23e7fc00-962e-11eb-816b-610e5cba9f8b.png)
I just call a chaincode transaction twice like this all of parameters all same. And I got this error message.
So does it illegal to call transactions with same parameters or  just somethings else happened?
![image](https://user-images.githubusercontent.com/47651330/113556009-6578a700-962e-11eb-8f4b-fad4bf83f22a.png)

And log messages are as follow.
![image](https://user-images.githubusercontent.com/47651330/113556215-bbe5e580-962e-11eb-9a1f-2abf1909df2d.png)

**Comment by TrueAbc** [comment]
I just called put_state to store a k-v pair in a init function for chaincode and then I want to update the same k-v pair using put_state. But I got mismatch hash error.

This is what init function has done.
![image](https://user-images.githubusercontent.com/47651330/113733300-e918bd80-972c-11eb-9b4b-62c6534770b3.png)
![image](https://user-images.githubusercontent.com/47651330/113733384-fdf55100-972c-11eb-8c96-887f3dc5b4f8.png)


And I called another transaction in which the same k-v pair stored in init function would be updated.
![image](https://user-images.githubusercontent.com/47651330/113733547-2715e180-972d-11eb-8242-82fae8477f08.png)

Here's the chaincode log.
![image](https://user-images.githubusercontent.com/47651330/113733691-490f6400-972d-11eb-940c-8cba55c9129b.png)

**Comment by TrueAbc** [comment]
To sum up, it seems that when I try to put a k-v pair that has been stored in world state. I got  hash mismatch error.

**Comment by mbrandenburger** [comment]
mh, this should not happen. Where exactly is the `hash mismatch error` thrown? I don't remember.

If we look at the FPC hello world tutorial, there we should be able to reproduce the issue you are reporting by simply calling the following command twice:

```
try ${PEER_CMD} chaincode invoke -o ${ORDERER_ADDR} -C ${CHAN_ID} -n ${CC_ID} -c '{"Args":["storeAsset","asset1","100"]}' --waitForEvent
```

Right? Could you please try this? 

Also, I've noticed that you are encrypting the arguments of the transaction before submitting them via our FPC SDK. Note that the FPC go SDK, by default, encrypts the transaction arguments as well as the transaction response, so you don't need to do that manually.

**Comment by TrueAbc** [comment]
> mh, this should not happen. Where exactly is the `hash mismatch error` thrown? I don't remember.
> 
> If we look at the FPC hello world tutorial, there we should be able to reproduce the issue you are reporting by simply calling the following command twice:

Yes, you are right. I think I need to find the real reason for this.



> Also, I've noticed that you are encrypting the arguments of the transaction before submitting them via our FPC SDK. Note that the FPC go SDK, by default, encrypts the transaction arguments as well as the transaction response, so you don't need to do that manually.

I have noticed that FPC has provided this feature. But I'm asked to implement key agreement based on Elliptic Curve Cryptosystem between chaincode and client-sdk. :confounded:

**Comment by TrueAbc** [comment]
Oh, this problem is caused by my chaincode logic.
I just transfer an uint8* var to get_state like this.
```c
    uint8_t* asset_bytes = new uint8_t[MAX_VALUE_SIZE];
    //
    get_state(asset_name.c_str(), asset_bytes, sizeof(asset_bytes), &asset_bytes_len, ctx);
```

And I changed this  in reference to example/aution and it worked.
```c
    // convert to json string and store
    std::string json = marshal_auction(&new_auction);
    put_state(auction_name.c_str(), (uint8_t*)json.c_str(), json.size(), ctx);



    // check if auction already exists
    uint32_t auction_bytes_len = 0;
    uint8_t auction_bytes[MAX_VALUE_SIZE];
    get_state(auction_name.c_str(), auction_bytes, sizeof(auction_bytes), &auction_bytes_len, ctx);

```
