### ISSUE TITLE
illegal instruction error crashed FPC chaincode when calling put_state

### ISSUE THREAD

**Issue by TrueAbc** [hyperledger-labs/fabric-private-chaincode#561]
I'm calling put_state to store three k-v pairs to worldstate. But it seems that one of them crashed chaincode.
The commented out two lines  codes crashed chaincode(If I comment them out,  chaincode just works well).
![image](https://user-images.githubusercontent.com/47651330/114000135-49267580-988d-11eb-9562-a2a360374663.png)

Here's the values of  k-v pairs.
![image](https://user-images.githubusercontent.com/47651330/114001309-64de4b80-988e-11eb-8f99-9d2d3f651554.png)
The following is the error log.
![image](https://user-images.githubusercontent.com/47651330/114001394-79badf00-988e-11eb-8374-a9cec4c24541.png)

I'm confused why  ```{"owner":"org2admin","msp":"Org2MSP","asset_list":"[]"} ``` can't be stored into world state.

So does anyone know what's causing the problem

**Comment by bvavala** [comment]
Would you please rebase and test your work on top of PR #560 ? 
I suspect that that would solve your issue.

**Comment by mbrandenburger** [comment]
Maybe this issue is related to the bug @bvavala has discovered and fixed with #560.

Can you maybe try to dig a bit deeper and see where exactly the enclave crashes? For instance, you could add a debug log [here](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/master/ecc_enclave/enclave/shim.cpp#L185) to see if we reach the ocall.

**Comment by TrueAbc** [comment]
I just dealt with this problem temporarily by passing an uint8_t pointer to put_state function. 
```c
            result = deleteWallet(&fromWallet, asset_name);
            uint8_t* temp = new uint8_t[result.size()+1];
            STRING_TO_POINTER(temp, result, result.size());
            LOG_DEBUG("from wallet in transfer:%s", result.c_str());
            put_state(fromWalletKey.c_str(), temp, result.size(), ctx);
```


> Would you please rebase and test your work on top of PR #560 ?
> I suspect that that would solve your issue.
And I will test my work later on this PR. I'm just an a deadline. :stuck_out_tongue_closed_eyes:

**Comment by mbrandenburger** [comment]
FYI PR #560 has been merged.

**Comment by TrueAbc** [comment]
I just tested my  work on PR #560. And you are right, this PR solved my issue.

> Would you please rebase and test your work on top of PR #560 ?
> I suspect that that would solve your issue.
