### ISSUE TITLE
Init enclaves for different organizations.

### ISSUE THREAD

**Issue by TrueAbc** [hyperledger-labs/fabric-private-chaincode#562]
For example in integration/test-network, we got a network with two organizations org1 and org2.
And we need to initialize enclave for chaincode before calling transactions. 
And here https://github.com/hyperledger-labs/fabric-private-chaincode/blob/37de010921cf28195942078c561d0bc4c0c41570/client_sdk/go/sample/main.go#L168-L172 we initialize enclave for org1.
It works well when I calling transactions as a member in org1. But if I act as a member in org2, I can't call transactions.(And when I want to initialize  enclave for org2,  i got error messages that enclave already initialized)

But if I just initialize enclave for org2 at beginning, I can call transactions as a  member of org2 instead of org1.

So do we need to init enclaves for different organizations separately or do something to deal with this situation?

When I want to init enclave for org2. I got his message.
![image](https://user-images.githubusercontent.com/47651330/114268267-d0f9b480-9a32-11eb-8879-e7701e1a4d24.png)
And here I use member in different orgs to call transactions.
User1 for org1. It worked will.
![image](https://user-images.githubusercontent.com/47651330/114268415-84fb3f80-9a33-11eb-8d63-385fd68cbbfb.png)
User1 for org2. Got error message.
![image](https://user-images.githubusercontent.com/47651330/114268395-69903480-9a33-11eb-9082-3e8736654abd.png)

**Comment by bvavala** [comment]
> For example in integration/test-network, we got a network with two organizations org1 and org2.
> And we need to initialize enclave for chaincode before calling transactions.
> And here
> 
> https://github.com/hyperledger-labs/fabric-private-chaincode/blob/37de010921cf28195942078c561d0bc4c0c41570/client_sdk/go/sample/main.go#L168-L172
> 
> we initialize enclave for org1.

No: not _for org1_, rather _for that chaincode on the channel_, whose enclave happens to be at org1.

Right now, each FPC chaincode has a single enclave, located at one specific peer endpoint, which must be initialized once.

> It works well when I calling transactions as a member in org1. But if I act as a member in org2, I can't call transactions.(And when I want to initialize enclave for org2, i got error messages that enclave already initialized)

This is expected, because the enclave has already been initialized.

> But if I just initialize enclave for org2 at beginning, I can call transactions as a member of org2 instead of org1.

Again this is expected. You are initializing the enclave for that chaincode once at a peer of org2.
For that same chaincode, you will not be able to register another enclave.

Once an enclave is initialized and registered, you should be able to submit transactions from both orgs.

> So do we need to init enclaves for different organizations separately or do something to deal with this situation?

1. for any FPC chaincode, you must init one enclave just once (1 FPC chaincode, 1 enclave, 1 init call).
2. if an enclave is running at a peer in org1, you must initialize the enclave as a member of org1 -- i.e., a member of org2 cannot initialize an enclave of org1.

**Comment by TrueAbc** [comment]
But in my example, my org member in org2 can't submit transactions if enclave is initialized by org1. 
Here is the output of client side.
![image](https://user-images.githubusercontent.com/47651330/114290543-ef9f9000-9ab2-11eb-84c6-a708ebcfbbc9.png)

And I found that transactions submitted by member of org2 just stopped after contacting with ercc chaincode without any error message outputs. 
![image](https://user-images.githubusercontent.com/47651330/114290753-65f0c200-9ab4-11eb-9761-58e34724b423.png)

So I don't know what's wrong with this( Org 1 initialized enclave and members of Org 1 work well with enclave chaincode but not members of Org 2). Is there any suggesstion for this problem?

**Comment by TrueAbc** [comment]
I just tried other transaction and I got some error message on client-side,   chaincode-side kept still.
```Failed to evaluate: Failed to read opts: peer [peer0.org1.example.com] not found```
So is this some problem about my bad config ?
![image](https://user-images.githubusercontent.com/47651330/114305001-bb56be80-9b08-11eb-96f4-38542460bdb4.png)

**Comment by TrueAbc** [comment]
O，I think it's still a config missing.  For users of org2,  they use connection-org2.yaml to connect to chaincode enclave in org1, but this config file doesn't contain peers/peer0.org1.example.com. So sdk raise read opts error.

Add configs below of org1 and users of org2 can submit transactions to chaincode enclave in org1.
![image](https://user-images.githubusercontent.com/47651330/114328474-57b3ac00-9b6f-11eb-9004-e1fb1a807ad4.png)


> I just tried other transaction and I got some error message on client-side, chaincode-side kept still.
> `Failed to evaluate: Failed to read opts: peer [peer0.org1.example.com] not found`
> So is this some problem about my bad config ?

**Comment by mbrandenburger** [comment]
> It works well when I calling transactions as a member in org1. But if I act as a member in org2, I can't call transactions.(And when I want to initialize enclave for org2, i got error messages that enclave already initialized)

yes, this is expected as with FPC 1.0 we support only a single enclave per chaincode. Will will address this limitation in the future.

**Comment by mbrandenburger** [comment]
mmh, the SDK should be able to discover `peer0.org1` for "normal" transactions. Did you also you the FPC SDK to init the enclave?

**Comment by TrueAbc** [comment]
Yes, I just init enclave using FPC SDK like this.  But I don't know if  ```discover```  worked.
At least, memebers of org1 can submit transactions and get ```peer0.org2``` for endorsing. But  org2 members can't get ```peer0.org1``` for submiting transactions to enclave chaincode of org1. 

```go
		defer func() {
			err:=recover()
			if err!=nil {
				fmt.Println(err)
			}
		}()
		ccpPath := filepath.Join(
			testNetworkPath,
			"organizations",
			"peerOrganizations",
			"org1.example.com",
			"copy.yaml",
		)
		sdk, err := fabsdk.New(config.FromFile(filepath.Clean(ccpPath)))
		if err != nil {
			fmt.Println("failed to create sdk: ", err)
			return
		}
		defer sdk.Close()


		orgAdmin := "Admin"
		orgName := "org1"
		adminContext := sdk.Context(fabsdk.WithUser(orgAdmin), fabsdk.WithOrg(orgName))

		client, err := fpcmgmt.New(adminContext)
		if err != nil {
			fmt.Println("failed to create context: ", err, client)
			return
		}
		attestationParams, err := sgx.CreateAttestationParamsFromEnvironment()
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(ccID)
		initReq := resmgmt.LifecycleInitEnclaveRequest{
			ChaincodeID:         ccID,
			EnclavePeerEndpoint: "peer0.org1.example.com", // define the peer where we wanna init our enclave
			AttestationParams:   attestationParams,
		}
		fmt.Println("starting enclave init")
		initTxId, err := client.LifecycleInitEnclave("mychannel", initReq)
		if err != nil {
			fmt.Println(err)
		}
		fmt.Println(initTxId)
```

**Comment by mbrandenburger** [comment]
ah I think the problem is that our FPC Client SDK retrieves the enclave endpoint from the Enclave Registry and calls the underlying Fabric Gateway with a target option; and by default the gateway API tries to resolve the endpoint (and their credentials) using the user configuration.

**Comment by TrueAbc** [comment]
> ah I think the problem is that our FPC Client SDK retrieves the enclave endpoint from the Enclave Registry and calls the underlying Fabric Gateway with a target option; and by default the gateway API tries to resolve the endpoint (and their credentials) using the user configuration.

So is there a config option of discovering endpoints in network  when init a gateway object in this way?. 
```go
gw, err := gateway.Connect(
  gateway.WithConfig(config.FromFile(filepath.Clean(ccpPath))),
  gateway.WithIdentity(wallet, walletKey),
)
```

**Comment by mbrandenburger** [comment]
@TrueAbc discovering is enabled and also used. But if you specify the endorsing peers for a transaction, it seems that this requires that the endpoints are available in the local configuration. This also makes sense as the user already knows which peer to call. :) 

I think a proper solution would be to enhance our SDK implementation to first discover all peers that have the FPC chaincode installed and then pick the one returned by the Enclave Registry. I have the feeling which will require a bit of refactoring here and there.

For now I have created a PR that addresses the issue by documenting that the connection files must include the peer that hosts the enclave.
