### ISSUE TITLE
Unit test cleanup

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#68]

**Comment by mbrandenburger** [comment]
- ERCC attestation test is failing
- ERCC attestation test should mock connection to real IAS
- ERCC attestation tests need some more love; however, this package will be factored anyway, so we address full coverage testing later

**Comment by mbrandenburger** [comment]
ECC_ENCLAVE no test at all :/ tests needed for ...
- enclave/shim.cpp
- enclave/enclave.cpp 
- enclave/crypto.cpp
- sgxcclib/sgxcclib.c

enclave/auction will be moved somewhere with #69.

**Comment by mbrandenburger** [comment]
ECC need some more tests ...

- crypto/ecdsa.go 
- vscc/ecc_validation_logic.go

Moreover, `enclave_chaincode_test.go` shoudl also use a mock for enclave; this also allows to test ecc logic without having the enclave binaries compiled yet. However, `enclave_stub_test.go` should test with an actual enclave binary including. This may make tests in ecc_enclave redundant. @g2flyer WDYT?

**Comment by mbrandenburger** [comment]
Utils has no tests :/

**Comment by mbrandenburger** [comment]
tlcc_enclave is missing many chances to have unit tests ... 

There is a test which loads a set of blocks (created by an ordering service) and processes them. However, the test is not triggered with `make test`

**Comment by mbrandenburger** [comment]
tlcc comes with basic unit tests.

`enclave/enclave_stub_test.go` is not invoked yet with test target.

**Comment by mbrandenburger** [comment]
closed with #78
