### ISSUE TITLE
cleanup of 'make clean'

### ISSUE THREAD

**Issue by bvavala** [hyperledger-labs/fabric-private-chaincode#71]
-ercc force docker remove
-force rm in ecc_enclave
-force rm sgxcclib
-ecc docker stop check container exists
-docker rmi fails (requires 1 argument)
-tlcc rm enclave/ ... force it
-tlcc rm trustedledger ... force it
-check docker_image in ecc (patch below)
diff --git a/ecc/Makefile b/ecc/Makefile
index 7faef50..d2c0700 100644
--- a/ecc/Makefile
+++ b/ecc/Makefile
@@ -52,6 +52,7 @@ clean: docker-clean
 #      rm enclave/mrenclave.go

 docker:
+       @if [ -z "${DOCKER_IMAGE}" ]; then echo "ERROR: you have to run_action.sh first before invoking this target"; exit 1; fi
        $(DOCKER) build -t $(DOCKER_IMAGE) -f Dockerfile ..

 docker-run:

**Comment by mbrandenburger** [comment]
I dont think we should output an error saying one needs to run the auction script first. A more generic error message would be better. Like "ERROR: no docker image for ${ECC_NAME} found."

**Comment by mbrandenburger** [comment]
Is this complete with PR #75 ? Can we close it?

**Comment by bvavala** [comment]
Yes -- completed in PR #75
