### ISSUE TITLE
TOP variable in makefiles depends on caller's working directory

### ISSUE THREAD

**Issue by bvavala** [hyperledger-labs/fabric-private-chaincode#74]
Need to:
* set TOP to the path of the top level makefile
* export it for the other makefiles
* perhaps call it FPC_TOP_DIRECTORY

**Comment by g2flyer** [comment]
Hmm, don't you have a chicken'n'egg problem: you need TOP to find the top-level makefile (or more precisely, build.mk), so how can it be defined in the top-level and not in each makefile?   Regarding renaming, calling it TOP seems to me a general naming convention for nested makefiles but i have no fundamental problem renaming it (although i certainly wouldn't volunteer to do it myself :-)

**Comment by mbrandenburger** [comment]
What is the issue with the current top? 

I like short names. `FPC_TOP_DIRECTORY` is soo long.

**Comment by bvavala** [comment]
> Hmm, don't you have a chicken'n'egg problem: you need TOP to find the top-level makefile (or more precisely, build.mk), 

TOP is set in the Makefile, then used elsewhere.

> so how can it be defined in the top-level and not in each makefile? 

We can set the TOP variable based on the absolute path of the Makefile, which "is" in the top level folder by construction.
Then, we can export the variable for the other Makefiles. In this way, we don't have to redefine TOP with a relative path each time.

> Regarding renaming, calling it TOP seems to me a general naming convention for nested makefiles but i have no fundamental problem renaming it (although i certainly wouldn't volunteer to do it myself :-)

TOP seems too generic, though I agree that the other one is long.

**Comment by mbrandenburger** [comment]
I would like to reduce the number of required exported vars to a minimum. 

I would use the build system as follows:

- Initially, I want to hit `make` in the top-level dir and get everything to build.

- When I develop on a component, let's say `ercc` for instance. I would navigate to the ercc folder and hit make there. 

I personally don't have the need to call ercc make from somewhere else ... even though some people sometimes may want exactly this. 

What about getting rid of TOP at all and follow the make structure as you can find [here](https://github.com/intel/linux-sgx). Would that be possible?

**Comment by g2flyer** [comment]
> What about getting rid of TOP at all and follow the make structure as you can find [here](https://github.com/intel/linux-sgx). Would that be possible?

As far as i can see, we use TOP only to find the top-level build.mk. Of course we can drop the TOP and just directly include.  Defining TOP=.. and then doing include $(TOP)/..  seemed to me somewhat easier to read/maintain but i have no strong opinion on this.   But if we do include build.mk directly, where would we even need a (globally defined) TOP?

**Comment by bvavala** [comment]
closing now -- global make works, no compelling need to change TOP variable
