### ISSUE TITLE
allow FPC CC names other than "ecc"

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#86]
It actually does "work" (in a sense of that it does not fail) when run with different names but lots of code in tlcc and ercc seems to rely on the ns to be "ecc" for checks which probably are simply skipped if the name is different?

PS: Further qualification to "work".  It seems it works in that case somewhat randomly as if there is a race-condition somewhere.  Which probably also relates to all the sleeps in our tests which we might have to replace with something less brittle (i.e., checks that async action on ledger really happened correctly)

**Comment by mbrandenburger** [comment]
PR #108 fixes this issue.
