### ISSUE TITLE
logging should be in the shim, not in the auction

### ISSUE THREAD

**Issue by bvavala** [hyperledger-labs/fabric-private-chaincode#88]

**Comment by mbrandenburger** [comment]
here we have the reference shim we need to follow. https://github.com/hyperledger/fabric/blob/13447bf5ead693f07285ce63a1903c5d0d25f096/core/chaincode/shim/interfaces_stable.go

I guess what you are supposing is, that we want to extend the shim in a way that the chaincode developer can perform logging easily.

Currently, a chaincode developer can just include `common/logging.h` and use `LOG_DEBUG`, `LOG_INFO`, and `LOG_ERROR`.

**Comment by g2flyer** [comment]
Clearly we don't want to add new bell's and whistle for logging, just (a) i think FPC chaincode should only use services from shim.h when interacting with infrastructure and (b) the logging namespace should be separated between logging done by the shim itself vs logging done by the FPC chaincode.

**Comment by mbrandenburger** [comment]
yes, this sounds right to me

**Comment by g2flyer** [comment]
On a related note: while logging functionality should move to shim.h, shim.h seems to contain a number of function which seem internal and not targeted to chaincode (e.g., all the rwset functions). They should be moved out of the shim.   Also, if we have unmarshall functions for inputs, shouldn't we have corresponding marshall functions for results? Seems strange to have only one but not the other ...

Lastly (but more long-term), we probably also want some put_public_state function?

**Comment by g2flyer** [comment]
Observations on #137 prototypes by Marcus ...
> Seems this is aligned with Fabric 1.4.x. This is good.
>
> In Fabric 2.0, however, chaincode logging is the responsibility by the chaincode developer.
https://hyperledger-fabric.readthedocs.io/en/master/logging-control.html
>
> Since this is not easily possible with FPC I still think its a good idea to provide this logging to the user. I believe we can only reduce the number of different log levels we want to support. Maybe just ERROR | WARNING | INFO | DEBUG ?

We definitely still should have logging-level edl functions as eventually with our own untrusted stub/shim we still want to be able to route (trusted) shim log-messages to peer. Given that we do not really have a full libc available, i think we also still would have to provide some logging functionality to user, but then on untrusted side might just throw it directly to stdout (rather than as right now to logger which then passes it to stdout ..)

**Comment by g2flyer** [comment]
This might be semi-obsolete for fabric v2 as chaincode logging completely disappeared and everything is "punted" to stdout/stderr.  Although given that by default an enclave doesn't have stdout/stderr, we might though still have some "official" debug api (or at least officially promote printing to stdout/stderr to shim.h?

**Comment by mbrandenburger** [comment]
> This might be semi-obsolete for fabric v2 as chaincode logging completely disappeared and everything is "punted" to stdout/stderr. Although given that by default an enclave doesn't have stdout/stderr, we might though still have some "official" debug api (or at least officially promote printing to stdout/stderr to shim.h?

ack - FPC should provide a simple logging API for debugging. I would say keeping `logging.h` and give FPC chaincode developers the chance to include it whenever they need it.
