### ISSUE TITLE
should parson be exposed to the chaincode app?

### ISSUE THREAD

**Issue by bvavala** [hyperledger-labs/fabric-private-chaincode#89]
pro:
* it is only included when the chaincode needs that

cons:
* it's a dependency external to the shim

other question:
* does every chaincode need it? If so, better put it in the shim

**Comment by mbrandenburger** [comment]
how do we use it currently?

1.  the auction example uses json to serialize its data structures. From the chaincode developer perspective, any other serialization could be used. Therefore, parson should not be exposed by the shim.

2. invocation arguments are provided as json and therefore the shim requires parson. values retrieved by getState are also provided as json

**Comment by mbrandenburger** [comment]
I think a chaincode app should include parson as a dependency if required.

**Comment by g2flyer** [comment]
I agree in general anything the shim uses internal and is not really something we want to force onto the FPC chaincode, we should keep internally even if some chaincode might use it as well. On the other hand, anything only FPC chaincode uses, should just stay with example.  The assumption here of course is that in case FPC chaincode uses same library as shim, dual instantiation of library doesn't bring any technical problems ..

**Comment by mbrandenburger** [comment]
Closed as we it seems we came to an agreement. #83 and #69 will take this design decision into account. If further discussion is needed please re-open.
